// Code generated by gen_typescript. DO NOT EDIT.

/**
 * ingredient state attribute types
 */
export const ALL_VALID_INGREDIENT_STATE_ATTRIBUTE_TYPES: string[] = [
  'texture',
  'consistency',
  'color',
  'appearance',
  'odor',
  'taste',
  'sound',
  'other',
];
type ValidIngredientStateAttributeTypeTypeTuple = typeof ALL_VALID_INGREDIENT_STATE_ATTRIBUTE_TYPES;
export type ValidIngredientStateAttributeType = ValidIngredientStateAttributeTypeTypeTuple[number];

/**
 * meal plan statuses
 */
export const ALL_VALID_MEAL_PLAN_STATUSES: string[] = ['awaiting_votes', 'finalized'];
type ValidMealPlanStatusTypeTuple = typeof ALL_VALID_MEAL_PLAN_STATUSES;
export type ValidMealPlanStatus = ValidMealPlanStatusTypeTuple[number];

/**
 * meal plan election methods
 */
export const ALL_VALID_MEAL_PLAN_ELECTION_METHODS: string[] = ['schulze', 'instant-runoff'];
type ValidMealPlanElectionMethodTypeTuple = typeof ALL_VALID_MEAL_PLAN_ELECTION_METHODS;
export type ValidMealPlanElectionMethod = ValidMealPlanElectionMethodTypeTuple[number];

/**
 * recipe step product types
 */
export const ALL_RECIPE_STEP_PRODUCT_TYPES: string[] = ['ingredient', 'instrument', 'vessel'];
type ValidRecipeStepProductTypeTypeTuple = typeof ALL_RECIPE_STEP_PRODUCT_TYPES;
export type ValidRecipeStepProductType = ValidRecipeStepProductTypeTypeTuple[number];

/**
 * meal component types
 */
export const ALL_MEAL_COMPONENT_TYPES: string[] = [
  'main',
  'side',
  'appetizer',
  'beverage',
  'dessert',
  'soup',
  'salad',
  'amuse-bouche',
  'unspecified',
];
type MealComponentTypeTypeTuple = typeof ALL_MEAL_COMPONENT_TYPES;
export type MealComponentType = MealComponentTypeTypeTuple[number];
