// Code generated by gen_typescript. DO NOT EDIT.

// valid ingredient state attribute types
export const ALL_VALID_INGREDIENT_STATE_ATTRIBUTE_TYPES: string[] = [
  'texture',
  'consistency',
  'color',
  'appearance',
  'odor',
  'taste',
  'sound',
  'other',
];

type ValidIngredientStateAttributeTypeTuple = typeof ALL_VALID_INGREDIENT_STATE_ATTRIBUTE_TYPES;
export type ValidIngredientStateAttributeType = ValidIngredientStateAttributeTypeTuple[number];

// meal plan statuses
export const ALL_VALID_MEAL_PLAN_STATUSES: string[] = ['awaiting_votes', 'finalized'];
type ValidMealPlanStatusTypeTuple = typeof ALL_VALID_MEAL_PLAN_STATUSES;
export type ValidMealPlanStatus = ValidMealPlanStatusTypeTuple[number];

// meal plan election methods
export const ALL_VALID_MEAL_PLAN_ELECTION_METHODS: string[] = ['schulze', 'instant-runoff'];
type ValidMealPlanElectionMethodTypeTuple = typeof ALL_VALID_MEAL_PLAN_ELECTION_METHODS;
export type ValidMealPlanElectionMethod = ValidMealPlanElectionMethodTypeTuple[number];

// recipe step product types
export const ALL_RECIPE_STEP_PRODUCT_TYPES = ['instrument', 'ingredient'];
type ValidRecipeStepProductTypeTuple = typeof ALL_RECIPE_STEP_PRODUCT_TYPES;
export type ValidRecipeStepProductType = ValidRecipeStepProductTypeTuple[number];

// meal component types
export const ALL_MEAL_COMPONENT_TYPES = [
  'main',
  'side',
  'appetizer',
  'beverage',
  'dessert',
  'soup',
  'salad',
  'amuse-bouche',
  'unspecified',
];

type MealComponentTypeTuple = typeof ALL_MEAL_COMPONENT_TYPES;
export type MealComponentType = MealComponentTypeTuple[number];
