// Code generated by gen_typescript. DO NOT EDIT.

export interface IModifyUserPermissionsInput {
  reason: NonNullable<string>;
  newRoles: NonNullable<string>;
}

export class ModifyUserPermissionsInput implements IModifyUserPermissionsInput {
  reason: NonNullable<string> = '';
  newRoles: NonNullable<string> = '';

  constructor(
    input: {
      reason?: string;
      newRoles?: string;
    } = {},
  ) {
    this.reason = input.reason ?? '';
    this.newRoles = input.newRoles ?? '';
  }
}
