// Code generated by gen_typescript. DO NOT EDIT.

export interface IAPIClient {
  createdAt: NonNullable<string>;
  lastUpdatedAt?: string;
  archivedAt?: string;
  name: NonNullable<string>;
  clientID: NonNullable<string>;
  id: NonNullable<string>;
  belongsToUser: NonNullable<string>;
}

export class APIClient implements IAPIClient {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  lastUpdatedAt?: string;
  archivedAt?: string;
  name: NonNullable<string> = '';
  clientID: NonNullable<string> = '';
  id: NonNullable<string> = '';
  belongsToUser: NonNullable<string> = '';

  constructor(
    input: {
      createdAt?: string;
      lastUpdatedAt?: string;
      archivedAt?: string;
      name?: string;
      clientID?: string;
      id?: string;
      belongsToUser?: string;
    } = {},
  ) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.archivedAt = input.archivedAt;
    this.name = input.name ?? '';
    this.clientID = input.clientID ?? '';
    this.id = input.id ?? '';
    this.belongsToUser = input.belongsToUser ?? '';
  }
}

export interface IAPIClientCreationRequestInput {
  username: NonNullable<string>;
  password: NonNullable<string>;
  totpToken: NonNullable<string>;
  clientName: NonNullable<string>;
}

export class APIClientCreationRequestInput implements IAPIClientCreationRequestInput {
  username: NonNullable<string> = '';
  password: NonNullable<string> = '';
  totpToken: NonNullable<string> = '';
  clientName: NonNullable<string> = '';

  constructor(
    input: {
      username?: string;
      password?: string;
      totpToken?: string;
      clientName?: string;
    } = {},
  ) {
    this.username = input.username ?? '';
    this.password = input.password ?? '';
    this.totpToken = input.totpToken ?? '';
    this.clientName = input.clientName ?? '';
  }
}

export interface IAPIClientCreationResponse {
  clientID: NonNullable<string>;
  clientSecret: NonNullable<string>;
  id: NonNullable<string>;
}

export class APIClientCreationResponse implements IAPIClientCreationResponse {
  clientID: NonNullable<string> = '';
  clientSecret: NonNullable<string> = '';
  id: NonNullable<string> = '';

  constructor(
    input: {
      clientID?: string;
      clientSecret?: string;
      id?: string;
    } = {},
  ) {
    this.clientID = input.clientID ?? '';
    this.clientSecret = input.clientSecret ?? '';
    this.id = input.id ?? '';
  }
}
