// Code generated by gen_typescript. DO NOT EDIT.

import { User } from './users';

export interface IHouseholdUserMembership {
  createdAt: NonNullable<string>;
  lastUpdatedAt?: string;
  archivedAt?: string;
  id: NonNullable<string>;
  belongsToUser: NonNullable<string>;
  belongsToHousehold: NonNullable<string>;
  householdRoles: NonNullable<string>;
  defaultHousehold: NonNullable<boolean>;
}

export class HouseholdUserMembership implements IHouseholdUserMembership {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  lastUpdatedAt?: string;
  archivedAt?: string;
  id: NonNullable<string> = '';
  belongsToUser: NonNullable<string> = '';
  belongsToHousehold: NonNullable<string> = '';
  householdRoles: NonNullable<string> = '';
  defaultHousehold: NonNullable<boolean> = false;

  constructor(
    input: {
      createdAt?: string;
      lastUpdatedAt?: string;
      archivedAt?: string;
      id?: string;
      belongsToUser?: string;
      belongsToHousehold?: string;
      householdRoles?: string;
      defaultHousehold?: boolean;
    } = {},
  ) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.archivedAt = input.archivedAt;
    this.id = input.id ?? '';
    this.belongsToUser = input.belongsToUser ?? '';
    this.belongsToHousehold = input.belongsToHousehold ?? '';
    this.householdRoles = input.householdRoles ?? '';
    this.defaultHousehold = input.defaultHousehold ?? false;
  }
}

export interface IHouseholdUserMembershipWithUser {
  createdAt: NonNullable<string>;
  lastUpdatedAt?: string;
  belongsToUser?: User;
  archivedAt?: string;
  id: NonNullable<string>;
  belongsToHousehold: NonNullable<string>;
  householdRoles: NonNullable<string>;
  defaultHousehold: NonNullable<boolean>;
}

export class HouseholdUserMembershipWithUser implements IHouseholdUserMembershipWithUser {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  lastUpdatedAt?: string;
  belongsToUser?: User = new User();
  archivedAt?: string;
  id: NonNullable<string> = '';
  belongsToHousehold: NonNullable<string> = '';
  householdRoles: NonNullable<string> = '';
  defaultHousehold: NonNullable<boolean> = false;

  constructor(
    input: {
      createdAt?: string;
      lastUpdatedAt?: string;
      belongsToUser?: User;
      archivedAt?: string;
      id?: string;
      belongsToHousehold?: string;
      householdRoles?: string;
      defaultHousehold?: boolean;
    } = {},
  ) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.belongsToUser = input.belongsToUser ?? new User();
    this.archivedAt = input.archivedAt;
    this.id = input.id ?? '';
    this.belongsToHousehold = input.belongsToHousehold ?? '';
    this.householdRoles = input.householdRoles ?? '';
    this.defaultHousehold = input.defaultHousehold ?? false;
  }
}

export interface IHouseholdUserMembershipCreationRequestInput {
  reason: NonNullable<string>;
  userID: NonNullable<string>;
}

export class HouseholdUserMembershipCreationRequestInput implements IHouseholdUserMembershipCreationRequestInput {
  reason: NonNullable<string> = '';
  userID: NonNullable<string> = '';

  constructor(
    input: {
      reason?: string;
      userID?: string;
    } = {},
  ) {
    this.reason = input.reason ?? '';
    this.userID = input.userID ?? '';
  }
}
