// Code generated by gen_typescript. DO NOT EDIT.

import { HouseholdUserMembershipWithUser } from './householdUserMemberships';

export interface IHousehold {
  createdAt: NonNullable<string>;
  subscriptionPlanID?: number;
  lastUpdatedAt?: string;
  archivedAt?: string;
  contactPhone: NonNullable<string>;
  billingStatus: NonNullable<string>;
  contactEmail: NonNullable<string>;
  paymentProcessorCustomer: NonNullable<string>;
  belongsToUser: NonNullable<string>;
  id: NonNullable<string>;
  timeZone: NonNullable<string>;
  name: NonNullable<string>;
  members: NonNullable<Array<HouseholdUserMembershipWithUser>>;
}

export class Household implements IHousehold {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  subscriptionPlanID?: number;
  lastUpdatedAt?: string;
  archivedAt?: string;
  contactPhone: NonNullable<string> = '';
  billingStatus: NonNullable<string> = '';
  contactEmail: NonNullable<string> = '';
  paymentProcessorCustomer: NonNullable<string> = '';
  belongsToUser: NonNullable<string> = '';
  id: NonNullable<string> = '';
  timeZone: NonNullable<string> = '';
  name: NonNullable<string> = '';
  members: NonNullable<Array<HouseholdUserMembershipWithUser>> = [];

  constructor(input: Partial<Household> = {}) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.subscriptionPlanID = input.subscriptionPlanID;
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.archivedAt = input.archivedAt;
    this.contactPhone = input.contactPhone ?? '';
    this.billingStatus = input.billingStatus ?? '';
    this.contactEmail = input.contactEmail ?? '';
    this.paymentProcessorCustomer = input.paymentProcessorCustomer ?? '';
    this.belongsToUser = input.belongsToUser ?? '';
    this.id = input.id ?? '';
    this.timeZone = input.timeZone ?? '';
    this.name = input.name ?? '';
    this.members = input.members ?? [];
  }
}

export interface IHouseholdCreationRequestInput {
  name: NonNullable<string>;
  contactEmail: NonNullable<string>;
  contactPhone: NonNullable<string>;
  timeZone: NonNullable<string>;
}

export class HouseholdCreationRequestInput implements IHouseholdCreationRequestInput {
  name: NonNullable<string> = '';
  contactEmail: NonNullable<string> = '';
  contactPhone: NonNullable<string> = '';
  timeZone: NonNullable<string> = '';

  constructor(input: Partial<HouseholdCreationRequestInput> = {}) {
    this.name = input.name ?? '';
    this.contactEmail = input.contactEmail ?? '';
    this.contactPhone = input.contactPhone ?? '';
    this.timeZone = input.timeZone ?? '';
  }
}

export interface IHouseholdUpdateRequestInput {
  name?: string;
  contactEmail?: string;
  contactPhone?: string;
  timeZone?: string;
}

export class HouseholdUpdateRequestInput implements IHouseholdUpdateRequestInput {
  name?: string;
  contactEmail?: string;
  contactPhone?: string;
  timeZone?: string;

  constructor(input: Partial<HouseholdUpdateRequestInput> = {}) {
    this.name = input.name;
    this.contactEmail = input.contactEmail;
    this.contactPhone = input.contactPhone;
    this.timeZone = input.timeZone;
  }
}

export interface IHouseholdOwnershipTransferInput {
  reason: NonNullable<string>;
  currentOwner: NonNullable<string>;
  newOwner: NonNullable<string>;
}

export class HouseholdOwnershipTransferInput implements IHouseholdOwnershipTransferInput {
  reason: NonNullable<string> = '';
  currentOwner: NonNullable<string> = '';
  newOwner: NonNullable<string> = '';

  constructor(input: Partial<HouseholdOwnershipTransferInput> = {}) {
    this.reason = input.reason ?? '';
    this.currentOwner = input.currentOwner ?? '';
    this.newOwner = input.newOwner ?? '';
  }
}
