// Code generated by gen_typescript. DO NOT EDIT.

import { MealComponent, MealComponentCreationRequestInput, MealComponentUpdateRequestInput } from './mealComponents';

export interface IMeal {
  createdAt: NonNullable<string>;
  archivedAt?: string;
  lastUpdatedAt?: string;
  id: NonNullable<string>;
  description: NonNullable<string>;
  createdByUser: NonNullable<string>;
  name: NonNullable<string>;
  components: NonNullable<Array<MealComponent>>;
}

export class Meal implements IMeal {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  archivedAt?: string;
  lastUpdatedAt?: string;
  id: NonNullable<string> = '';
  description: NonNullable<string> = '';
  createdByUser: NonNullable<string> = '';
  name: NonNullable<string> = '';
  components: NonNullable<Array<MealComponent>> = [];

  constructor(
    input: {
      createdAt?: string;
      archivedAt?: string;
      lastUpdatedAt?: string;
      id?: string;
      description?: string;
      createdByUser?: string;
      name?: string;
      components?: MealComponent[];
    } = {},
  ) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.archivedAt = input.archivedAt;
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.id = input.id ?? '';
    this.description = input.description ?? '';
    this.createdByUser = input.createdByUser ?? '';
    this.name = input.name ?? '';
    this.components = input.components ?? [];
  }
}

export interface IMealCreationRequestInput {
  name: NonNullable<string>;
  description: NonNullable<string>;
  recipes: NonNullable<Array<MealComponentCreationRequestInput>>;
}

export class MealCreationRequestInput implements IMealCreationRequestInput {
  name: NonNullable<string> = '';
  description: NonNullable<string> = '';
  recipes: NonNullable<Array<MealComponentCreationRequestInput>> = [];

  constructor(
    input: {
      name?: string;
      description?: string;
      recipes?: MealComponentCreationRequestInput[];
    } = {},
  ) {
    this.name = input.name ?? '';
    this.description = input.description ?? '';
    this.recipes = input.recipes ?? [];
  }
}

export interface IMealUpdateRequestInput {
  name?: string;
  description?: string;
  recipes: NonNullable<Array<MealComponentUpdateRequestInput>>;
}

export class MealUpdateRequestInput implements IMealUpdateRequestInput {
  name?: string;
  description?: string;
  recipes: NonNullable<Array<MealComponentUpdateRequestInput>> = [];

  constructor(
    input: {
      name?: string;
      description?: string;
      recipes?: MealComponentUpdateRequestInput[];
    } = {},
  ) {
    this.name = input.name;
    this.description = input.description;
    this.recipes = input.recipes ?? [];
  }
}
