// Code generated by gen_typescript. DO NOT EDIT.

import { Recipe } from './recipes';

export interface IMealComponent {
  componentType: NonNullable<string>;
  recipe: NonNullable<Recipe>;
}

export class MealComponent implements IMealComponent {
  componentType: NonNullable<string> = '';
  recipe: NonNullable<Recipe> = new Recipe();

  constructor(
    input: {
      componentType?: string;
      recipe?: Recipe;
    } = {},
  ) {
    this.componentType = input.componentType ?? '';
    this.recipe = input.recipe ?? new Recipe();
  }
}

export interface IMealComponentCreationRequestInput {
  recipeID: NonNullable<string>;
  mealComponentType: NonNullable<string>;
}

export class MealComponentCreationRequestInput implements IMealComponentCreationRequestInput {
  recipeID: NonNullable<string> = '';
  mealComponentType: NonNullable<string> = '';

  constructor(
    input: {
      recipeID?: string;
      mealComponentType?: string;
    } = {},
  ) {
    this.recipeID = input.recipeID ?? '';
    this.mealComponentType = input.mealComponentType ?? '';
  }
}

export interface IMealComponentUpdateRequestInput {
  recipeID: NonNullable<string>;
  mealComponentType: NonNullable<string>;
}

export class MealComponentUpdateRequestInput implements IMealComponentUpdateRequestInput {
  recipeID: NonNullable<string> = '';
  mealComponentType: NonNullable<string> = '';

  constructor(
    input: {
      recipeID?: string;
      mealComponentType?: string;
    } = {},
  ) {
    this.recipeID = input.recipeID ?? '';
    this.mealComponentType = input.mealComponentType ?? '';
  }
}
