// Code generated by gen_typescript. DO NOT EDIT.

import { MealPlanEvent, MealPlanEventCreationRequestInput } from './mealPlanEvents';

export interface IMealPlan {
  createdAt: NonNullable<string>;
  votingDeadline: NonNullable<string>;
  archivedAt?: string;
  lastUpdatedAt?: string;
  status: NonNullable<string>;
  id: NonNullable<string>;
  notes: NonNullable<string>;
  electionMethod: NonNullable<string>;
  belongsToHousehold: NonNullable<string>;
  events: NonNullable<Array<MealPlanEvent>>;
  groceryListInitialized: NonNullable<boolean>;
  tasksCreated: NonNullable<boolean>;
}

export class MealPlan implements IMealPlan {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  votingDeadline: NonNullable<string> = '1970-01-01T00:00:00Z';
  archivedAt?: string;
  lastUpdatedAt?: string;
  status: NonNullable<string> = '';
  id: NonNullable<string> = '';
  notes: NonNullable<string> = '';
  electionMethod: NonNullable<string> = '';
  belongsToHousehold: NonNullable<string> = '';
  events: NonNullable<Array<MealPlanEvent>> = [];
  groceryListInitialized: NonNullable<boolean> = false;
  tasksCreated: NonNullable<boolean> = false;

  constructor(
    input: {
      createdAt?: string;
      votingDeadline?: string;
      archivedAt?: string;
      lastUpdatedAt?: string;
      status?: string;
      id?: string;
      notes?: string;
      electionMethod?: string;
      belongsToHousehold?: string;
      events?: MealPlanEvent[];
      groceryListInitialized?: boolean;
      tasksCreated?: boolean;
    } = {},
  ) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.votingDeadline = input.votingDeadline ?? '1970-01-01T00:00:00Z';
    this.archivedAt = input.archivedAt;
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.status = input.status ?? '';
    this.id = input.id ?? '';
    this.notes = input.notes ?? '';
    this.electionMethod = input.electionMethod ?? '';
    this.belongsToHousehold = input.belongsToHousehold ?? '';
    this.events = input.events ?? [];
    this.groceryListInitialized = input.groceryListInitialized ?? false;
    this.tasksCreated = input.tasksCreated ?? false;
  }
}

export interface IMealPlanCreationRequestInput {
  votingDeadline: NonNullable<string>;
  notes: NonNullable<string>;
  electionMethod: NonNullable<string>;
  events: NonNullable<Array<MealPlanEventCreationRequestInput>>;
}

export class MealPlanCreationRequestInput implements IMealPlanCreationRequestInput {
  votingDeadline: NonNullable<string> = '1970-01-01T00:00:00Z';
  notes: NonNullable<string> = '';
  electionMethod: NonNullable<string> = '';
  events: NonNullable<Array<MealPlanEventCreationRequestInput>> = [];

  constructor(
    input: {
      votingDeadline?: string;
      notes?: string;
      electionMethod?: string;
      events?: MealPlanEventCreationRequestInput[];
    } = {},
  ) {
    this.votingDeadline = input.votingDeadline ?? '1970-01-01T00:00:00Z';
    this.notes = input.notes ?? '';
    this.electionMethod = input.electionMethod ?? '';
    this.events = input.events ?? [];
  }
}

export interface IMealPlanUpdateRequestInput {
  notes?: string;
  votingDeadline?: string;
}

export class MealPlanUpdateRequestInput implements IMealPlanUpdateRequestInput {
  notes?: string;
  votingDeadline?: string;

  constructor(
    input: {
      notes?: string;
      votingDeadline?: string;
    } = {},
  ) {
    this.notes = input.notes;
    this.votingDeadline = input.votingDeadline;
  }
}
