// Code generated by gen_typescript. DO NOT EDIT.

import { MealComponentType } from './_unions';
import { Recipe } from './recipes';

export interface IMealComponent {
  componentType: NonNullable<MealComponentType>;
  recipe: NonNullable<Recipe>;
}

export class MealComponent implements IMealComponent {
  componentType: NonNullable<MealComponentType> = 'unspecified';
  recipe: NonNullable<Recipe> = new Recipe();

  constructor(input: Partial<MealComponent> = {}) {
    this.componentType = input.componentType ?? 'unspecified';
    this.recipe = input.recipe ?? new Recipe();
  }
}

export interface IMealComponentCreationRequestInput {
  recipeID: NonNullable<string>;
  componentType: NonNullable<MealComponentType>;
}

export class MealComponentCreationRequestInput implements IMealComponentCreationRequestInput {
  recipeID: NonNullable<string> = '';
  componentType: NonNullable<MealComponentType> = 'unspecified';

  constructor(input: Partial<MealComponentCreationRequestInput> = {}) {
    this.recipeID = input.recipeID ?? '';
    this.componentType = input.componentType ?? 'unspecified';
  }
}

export interface IMealComponentUpdateRequestInput {
  recipeID: NonNullable<string>;
  componentType: NonNullable<MealComponentType>;
}

export class MealComponentUpdateRequestInput implements IMealComponentUpdateRequestInput {
  recipeID: NonNullable<string> = '';
  componentType: NonNullable<MealComponentType> = 'unspecified';

  constructor(input: Partial<MealComponentUpdateRequestInput> = {}) {
    this.recipeID = input.recipeID ?? '';
    this.componentType = input.componentType ?? 'unspecified';
  }
}
