// Code generated by gen_typescript. DO NOT EDIT.

export interface IUserPermissionsRequestInput {
  permissions: NonNullable<Array<string>>;
}

export class UserPermissionsRequestInput implements IUserPermissionsRequestInput {
  permissions: NonNullable<Array<string>> = [];

  constructor(
    input: {
      permissions?: string[];
    } = {},
  ) {
    this.permissions = input.permissions ?? [];
  }
}

export interface IUserPermissionsResponse {
  permissions: NonNullable<Record<string, boolean>>;
}

export class UserPermissionsResponse implements IUserPermissionsResponse {
  permissions: NonNullable<Record<string, boolean>> = {};

  constructor(
    input: {
      permissions?: Record<string, boolean>;
    } = {},
  ) {
    this.permissions = input.permissions ?? {};
  }
}
