// Code generated by gen_typescript. DO NOT EDIT.

import { RecipeMedia } from './recipeMedia';
import { RecipePrepTask, RecipePrepTaskWithinRecipeCreationRequestInput } from './recipePrepTasks';
import { RecipeStep, RecipeStepCreationRequestInput } from './recipeSteps';

export interface IRecipe {
  createdAt: NonNullable<string>;
  inspiredByRecipeID?: string;
  lastUpdatedAt?: string;
  archivedAt?: string;
  maximumEstimatedPortions?: number;
  id: NonNullable<string>;
  slug: NonNullable<string>;
  name: NonNullable<string>;
  portionName: NonNullable<string>;
  pluralPortionName: NonNullable<string>;
  createdByUser: NonNullable<string>;
  source: NonNullable<string>;
  description: NonNullable<string>;
  yieldsComponentType: NonNullable<string>;
  prepTasks: NonNullable<Array<RecipePrepTask>>;
  steps: NonNullable<Array<RecipeStep>>;
  media: NonNullable<Array<RecipeMedia>>;
  minimumEstimatedPortions: NonNullable<number>;
  sealOfApproval: NonNullable<boolean>;
  eligibleForMeals: NonNullable<boolean>;
}

export class Recipe implements IRecipe {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  inspiredByRecipeID?: string;
  lastUpdatedAt?: string;
  archivedAt?: string;
  maximumEstimatedPortions?: number;
  id: NonNullable<string> = '';
  slug: NonNullable<string> = '';
  name: NonNullable<string> = '';
  portionName: NonNullable<string> = '';
  pluralPortionName: NonNullable<string> = '';
  createdByUser: NonNullable<string> = '';
  source: NonNullable<string> = '';
  description: NonNullable<string> = '';
  yieldsComponentType: NonNullable<string> = '';
  prepTasks: NonNullable<Array<RecipePrepTask>> = [];
  steps: NonNullable<Array<RecipeStep>> = [];
  media: NonNullable<Array<RecipeMedia>> = [];
  minimumEstimatedPortions: NonNullable<number> = 0;
  sealOfApproval: NonNullable<boolean> = false;
  eligibleForMeals: NonNullable<boolean> = false;

  constructor(input: Partial<Recipe> = {}) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.inspiredByRecipeID = input.inspiredByRecipeID;
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.archivedAt = input.archivedAt;
    this.maximumEstimatedPortions = input.maximumEstimatedPortions;
    this.id = input.id ?? '';
    this.slug = input.slug ?? '';
    this.name = input.name ?? '';
    this.portionName = input.portionName ?? '';
    this.pluralPortionName = input.pluralPortionName ?? '';
    this.createdByUser = input.createdByUser ?? '';
    this.source = input.source ?? '';
    this.description = input.description ?? '';
    this.yieldsComponentType = input.yieldsComponentType ?? '';
    this.prepTasks = input.prepTasks ?? [];
    this.steps = input.steps ?? [];
    this.media = input.media ?? [];
    this.minimumEstimatedPortions = input.minimumEstimatedPortions ?? 0;
    this.sealOfApproval = input.sealOfApproval ?? false;
    this.eligibleForMeals = input.eligibleForMeals ?? false;
  }
}

export interface IRecipeCreationRequestInput {
  inspiredByRecipeID?: string;
  maximumEstimatedPortions?: number;
  portionName: NonNullable<string>;
  source: NonNullable<string>;
  description: NonNullable<string>;
  pluralPortionName: NonNullable<string>;
  name: NonNullable<string>;
  slug: NonNullable<string>;
  yieldsComponentType: NonNullable<string>;
  prepTasks: NonNullable<Array<RecipePrepTaskWithinRecipeCreationRequestInput>>;
  steps: NonNullable<Array<RecipeStepCreationRequestInput>>;
  minimumEstimatedPortions: NonNullable<number>;
  alsoCreateMeal: NonNullable<boolean>;
  sealOfApproval: NonNullable<boolean>;
  eligibleForMeals: NonNullable<boolean>;
}

export class RecipeCreationRequestInput implements IRecipeCreationRequestInput {
  inspiredByRecipeID?: string;
  maximumEstimatedPortions?: number;
  portionName: NonNullable<string> = '';
  source: NonNullable<string> = '';
  description: NonNullable<string> = '';
  pluralPortionName: NonNullable<string> = '';
  name: NonNullable<string> = '';
  slug: NonNullable<string> = '';
  yieldsComponentType: NonNullable<string> = '';
  prepTasks: NonNullable<Array<RecipePrepTaskWithinRecipeCreationRequestInput>> = [];
  steps: NonNullable<Array<RecipeStepCreationRequestInput>> = [];
  minimumEstimatedPortions: NonNullable<number> = 0;
  alsoCreateMeal: NonNullable<boolean> = false;
  sealOfApproval: NonNullable<boolean> = false;
  eligibleForMeals: NonNullable<boolean> = false;

  constructor(input: Partial<RecipeCreationRequestInput> = {}) {
    this.inspiredByRecipeID = input.inspiredByRecipeID;
    this.maximumEstimatedPortions = input.maximumEstimatedPortions;
    this.portionName = input.portionName ?? '';
    this.source = input.source ?? '';
    this.description = input.description ?? '';
    this.pluralPortionName = input.pluralPortionName ?? '';
    this.name = input.name ?? '';
    this.slug = input.slug ?? '';
    this.yieldsComponentType = input.yieldsComponentType ?? '';
    this.prepTasks = input.prepTasks ?? [];
    this.steps = input.steps ?? [];
    this.minimumEstimatedPortions = input.minimumEstimatedPortions ?? 0;
    this.alsoCreateMeal = input.alsoCreateMeal ?? false;
    this.sealOfApproval = input.sealOfApproval ?? false;
    this.eligibleForMeals = input.eligibleForMeals ?? false;
  }
}

export interface IRecipeUpdateRequestInput {
  name?: string;
  slug?: string;
  source?: string;
  description?: string;
  inspiredByRecipeID?: string;
  sealOfApproval?: boolean;
  minimumEstimatedPortions?: number;
  maximumEstimatedPortions?: number;
  portionName?: string;
  pluralPortionName?: string;
  eligibleForMeals?: boolean;
  yieldsComponentType?: string;
}

export class RecipeUpdateRequestInput implements IRecipeUpdateRequestInput {
  name?: string;
  slug?: string;
  source?: string;
  description?: string;
  inspiredByRecipeID?: string;
  sealOfApproval?: boolean = false;
  minimumEstimatedPortions?: number;
  maximumEstimatedPortions?: number;
  portionName?: string;
  pluralPortionName?: string;
  eligibleForMeals?: boolean = false;
  yieldsComponentType?: string;

  constructor(input: Partial<RecipeUpdateRequestInput> = {}) {
    this.name = input.name;
    this.slug = input.slug;
    this.source = input.source;
    this.description = input.description;
    this.inspiredByRecipeID = input.inspiredByRecipeID;
    this.sealOfApproval = input.sealOfApproval ?? false;
    this.minimumEstimatedPortions = input.minimumEstimatedPortions;
    this.maximumEstimatedPortions = input.maximumEstimatedPortions;
    this.portionName = input.portionName;
    this.pluralPortionName = input.pluralPortionName;
    this.eligibleForMeals = input.eligibleForMeals ?? false;
    this.yieldsComponentType = input.yieldsComponentType;
  }
}
