// Code generated by gen_typescript. DO NOT EDIT.

import { ValidMeasurementUnit } from './validMeasurementUnits';

export interface IRecipeStepProduct {
  createdAt: NonNullable<string>;
  maximumStorageDurationInSeconds?: number;
  minimumStorageTemperatureInCelsius?: number;
  maximumStorageTemperatureInCelsius?: number;
  archivedAt?: string;
  lastUpdatedAt?: string;
  id: NonNullable<string>;
  type: NonNullable<string>;
  name: NonNullable<string>;
  storageInstructions: NonNullable<string>;
  quantityNotes: NonNullable<string>;
  belongsToRecipeStep: NonNullable<string>;
  measurementUnit: NonNullable<ValidMeasurementUnit>;
  maximumQuantity: NonNullable<number>;
  minimumQuantity: NonNullable<number>;
  isWaste: NonNullable<boolean>;
  isLiquid: NonNullable<boolean>;
  compostable: NonNullable<boolean>;
}

export class RecipeStepProduct implements IRecipeStepProduct {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  maximumStorageDurationInSeconds?: number;
  minimumStorageTemperatureInCelsius?: number;
  maximumStorageTemperatureInCelsius?: number;
  archivedAt?: string;
  lastUpdatedAt?: string;
  id: NonNullable<string> = '';
  type: NonNullable<string> = '';
  name: NonNullable<string> = '';
  storageInstructions: NonNullable<string> = '';
  quantityNotes: NonNullable<string> = '';
  belongsToRecipeStep: NonNullable<string> = '';
  measurementUnit: NonNullable<ValidMeasurementUnit> = new ValidMeasurementUnit();
  maximumQuantity: NonNullable<number> = -1;
  minimumQuantity: NonNullable<number> = -1;
  isWaste: NonNullable<boolean> = false;
  isLiquid: NonNullable<boolean> = false;
  compostable: NonNullable<boolean> = false;

  constructor(
    input: {
      createdAt?: string;
      maximumStorageDurationInSeconds?: number;
      minimumStorageTemperatureInCelsius?: number;
      maximumStorageTemperatureInCelsius?: number;
      archivedAt?: string;
      lastUpdatedAt?: string;
      id?: string;
      type?: string;
      name?: string;
      storageInstructions?: string;
      quantityNotes?: string;
      belongsToRecipeStep?: string;
      measurementUnit?: ValidMeasurementUnit;
      maximumQuantity?: number;
      minimumQuantity?: number;
      isWaste?: boolean;
      isLiquid?: boolean;
      compostable?: boolean;
    } = {},
  ) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.maximumStorageDurationInSeconds = input.maximumStorageDurationInSeconds;
    this.minimumStorageTemperatureInCelsius = input.minimumStorageTemperatureInCelsius;
    this.maximumStorageTemperatureInCelsius = input.maximumStorageTemperatureInCelsius;
    this.archivedAt = input.archivedAt;
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.id = input.id ?? '';
    this.type = input.type ?? '';
    this.name = input.name ?? '';
    this.storageInstructions = input.storageInstructions ?? '';
    this.quantityNotes = input.quantityNotes ?? '';
    this.belongsToRecipeStep = input.belongsToRecipeStep ?? '';
    this.measurementUnit = input.measurementUnit ?? new ValidMeasurementUnit();
    this.maximumQuantity = input.maximumQuantity ?? -1;
    this.minimumQuantity = input.minimumQuantity ?? -1;
    this.isWaste = input.isWaste ?? false;
    this.isLiquid = input.isLiquid ?? false;
    this.compostable = input.compostable ?? false;
  }
}

export interface IRecipeStepProductCreationRequestInput {
  minimumStorageTemperatureInCelsius?: number;
  maximumStorageTemperatureInCelsius?: number;
  maximumStorageDurationInSeconds?: number;
  type: NonNullable<string>;
  measurementUnitID: NonNullable<string>;
  quantityNotes: NonNullable<string>;
  name: NonNullable<string>;
  storageInstructions: NonNullable<string>;
  maximumQuantity: NonNullable<number>;
  minimumQuantity: NonNullable<number>;
  compostable: NonNullable<boolean>;
  isLiquid: NonNullable<boolean>;
  isWaste: NonNullable<boolean>;
}

export class RecipeStepProductCreationRequestInput implements IRecipeStepProductCreationRequestInput {
  minimumStorageTemperatureInCelsius?: number;
  maximumStorageTemperatureInCelsius?: number;
  maximumStorageDurationInSeconds?: number;
  type: NonNullable<string> = '';
  measurementUnitID: NonNullable<string> = '';
  quantityNotes: NonNullable<string> = '';
  name: NonNullable<string> = '';
  storageInstructions: NonNullable<string> = '';
  maximumQuantity: NonNullable<number> = -1;
  minimumQuantity: NonNullable<number> = -1;
  compostable: NonNullable<boolean> = false;
  isLiquid: NonNullable<boolean> = false;
  isWaste: NonNullable<boolean> = false;

  constructor(
    input: {
      minimumStorageTemperatureInCelsius?: number;
      maximumStorageTemperatureInCelsius?: number;
      maximumStorageDurationInSeconds?: number;
      type?: string;
      measurementUnitID?: string;
      quantityNotes?: string;
      name?: string;
      storageInstructions?: string;
      maximumQuantity?: number;
      minimumQuantity?: number;
      compostable?: boolean;
      isLiquid?: boolean;
      isWaste?: boolean;
    } = {},
  ) {
    this.minimumStorageTemperatureInCelsius = input.minimumStorageTemperatureInCelsius;
    this.maximumStorageTemperatureInCelsius = input.maximumStorageTemperatureInCelsius;
    this.maximumStorageDurationInSeconds = input.maximumStorageDurationInSeconds;
    this.type = input.type ?? '';
    this.measurementUnitID = input.measurementUnitID ?? '';
    this.quantityNotes = input.quantityNotes ?? '';
    this.name = input.name ?? '';
    this.storageInstructions = input.storageInstructions ?? '';
    this.maximumQuantity = input.maximumQuantity ?? -1;
    this.minimumQuantity = input.minimumQuantity ?? -1;
    this.compostable = input.compostable ?? false;
    this.isLiquid = input.isLiquid ?? false;
    this.isWaste = input.isWaste ?? false;
  }
}

export interface IRecipeStepProductUpdateRequestInput {
  name?: string;
  type?: string;
  measurementUnitID?: string;
  quantityNotes?: string;
  belongsToRecipeStep?: string;
  minimumQuantity?: number;
  maximumQuantity?: number;
  compostable?: boolean;
  maximumStorageDurationInSeconds?: number;
  minimumStorageTemperatureInCelsius?: number;
  maximumStorageTemperatureInCelsius?: number;
  storageInstructions?: string;
  isLiquid?: boolean;
  isWaste?: boolean;
}

export class RecipeStepProductUpdateRequestInput implements IRecipeStepProductUpdateRequestInput {
  name?: string;
  type?: string;
  measurementUnitID?: string;
  quantityNotes?: string;
  belongsToRecipeStep?: string;
  minimumQuantity?: number;
  maximumQuantity?: number;
  compostable?: boolean = false;
  maximumStorageDurationInSeconds?: number;
  minimumStorageTemperatureInCelsius?: number;
  maximumStorageTemperatureInCelsius?: number;
  storageInstructions?: string;
  isLiquid?: boolean = false;
  isWaste?: boolean = false;

  constructor(
    input: {
      name?: string;
      type?: string;
      measurementUnitID?: string;
      quantityNotes?: string;
      belongsToRecipeStep?: string;
      minimumQuantity?: number;
      maximumQuantity?: number;
      compostable?: boolean;
      maximumStorageDurationInSeconds?: number;
      minimumStorageTemperatureInCelsius?: number;
      maximumStorageTemperatureInCelsius?: number;
      storageInstructions?: string;
      isLiquid?: boolean;
      isWaste?: boolean;
    } = {},
  ) {
    this.name = input.name;
    this.type = input.type;
    this.measurementUnitID = input.measurementUnitID;
    this.quantityNotes = input.quantityNotes;
    this.belongsToRecipeStep = input.belongsToRecipeStep;
    this.minimumQuantity = input.minimumQuantity;
    this.maximumQuantity = input.maximumQuantity;
    this.compostable = input.compostable ?? false;
    this.maximumStorageDurationInSeconds = input.maximumStorageDurationInSeconds;
    this.minimumStorageTemperatureInCelsius = input.minimumStorageTemperatureInCelsius;
    this.maximumStorageTemperatureInCelsius = input.maximumStorageTemperatureInCelsius;
    this.storageInstructions = input.storageInstructions;
    this.isLiquid = input.isLiquid ?? false;
    this.isWaste = input.isWaste ?? false;
  }
}
