// Code generated by gen_typescript. DO NOT EDIT.

import { RecipeMedia } from './recipeMedia';
import { RecipePrepTask, RecipePrepTaskWithinRecipeCreationRequestInput } from './recipePrepTasks';
import { RecipeStep, RecipeStepCreationRequestInput } from './recipeSteps';

export interface IRecipe {
  createdAt: NonNullable<string>;
  inspiredByRecipeID?: string;
  lastUpdatedAt?: string;
  archivedAt?: string;
  portionName: NonNullable<string>;
  source: NonNullable<string>;
  description: NonNullable<string>;
  name: NonNullable<string>;
  id: NonNullable<string>;
  belongsToUser: NonNullable<string>;
  pluralPortionName: NonNullable<string>;
  media: NonNullable<Array<RecipeMedia>>;
  prepTasks: NonNullable<Array<RecipePrepTask>>;
  steps: NonNullable<Array<RecipeStep>>;
  sealOfApproval: NonNullable<boolean>;
  yieldsPortions: NonNullable<number>;
}

export class Recipe implements IRecipe {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  inspiredByRecipeID?: string;
  lastUpdatedAt?: string;
  archivedAt?: string;
  portionName: NonNullable<string> = '';
  source: NonNullable<string> = '';
  description: NonNullable<string> = '';
  name: NonNullable<string> = '';
  id: NonNullable<string> = '';
  belongsToUser: NonNullable<string> = '';
  pluralPortionName: NonNullable<string> = '';
  media: NonNullable<Array<RecipeMedia>> = [];
  prepTasks: NonNullable<Array<RecipePrepTask>> = [];
  steps: NonNullable<Array<RecipeStep>> = [];
  sealOfApproval: NonNullable<boolean> = false;
  yieldsPortions: NonNullable<number> = 0;

  constructor(input: Partial<Recipe> = {}) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.inspiredByRecipeID = input.inspiredByRecipeID;
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.archivedAt = input.archivedAt;
    this.portionName = input.portionName ?? '';
    this.source = input.source ?? '';
    this.description = input.description ?? '';
    this.name = input.name ?? '';
    this.id = input.id ?? '';
    this.belongsToUser = input.belongsToUser ?? '';
    this.pluralPortionName = input.pluralPortionName ?? '';
    this.media = input.media ?? [];
    this.prepTasks = input.prepTasks ?? [];
    this.steps = input.steps ?? [];
    this.sealOfApproval = input.sealOfApproval ?? false;
    this.yieldsPortions = input.yieldsPortions ?? 0;
  }
}

export interface IRecipeCreationRequestInput {
  inspiredByRecipeID?: string;
  name: NonNullable<string>;
  source: NonNullable<string>;
  description: NonNullable<string>;
  pluralPortionName: NonNullable<string>;
  portionName: NonNullable<string>;
  prepTasks: NonNullable<Array<RecipePrepTaskWithinRecipeCreationRequestInput>>;
  steps: NonNullable<Array<RecipeStepCreationRequestInput>>;
  alsoCreateMeal: NonNullable<boolean>;
  sealOfApproval: NonNullable<boolean>;
  yieldsPortions: NonNullable<number>;
}

export class RecipeCreationRequestInput implements IRecipeCreationRequestInput {
  inspiredByRecipeID?: string;
  name: NonNullable<string> = '';
  source: NonNullable<string> = '';
  description: NonNullable<string> = '';
  pluralPortionName: NonNullable<string> = '';
  portionName: NonNullable<string> = '';
  prepTasks: NonNullable<Array<RecipePrepTaskWithinRecipeCreationRequestInput>> = [];
  steps: NonNullable<Array<RecipeStepCreationRequestInput>> = [];
  alsoCreateMeal: NonNullable<boolean> = false;
  sealOfApproval: NonNullable<boolean> = false;
  yieldsPortions: NonNullable<number> = 0;

  constructor(input: Partial<RecipeCreationRequestInput> = {}) {
    this.inspiredByRecipeID = input.inspiredByRecipeID;
    this.name = input.name ?? '';
    this.source = input.source ?? '';
    this.description = input.description ?? '';
    this.pluralPortionName = input.pluralPortionName ?? '';
    this.portionName = input.portionName ?? '';
    this.prepTasks = input.prepTasks ?? [];
    this.steps = input.steps ?? [];
    this.alsoCreateMeal = input.alsoCreateMeal ?? false;
    this.sealOfApproval = input.sealOfApproval ?? false;
    this.yieldsPortions = input.yieldsPortions ?? 0;
  }
}

export interface IRecipeUpdateRequestInput {
  name?: string;
  source?: string;
  description?: string;
  inspiredByRecipeID?: string;
  sealOfApproval?: boolean;
  yieldsPortions?: number;
  portionName?: string;
  pluralPortionName?: string;
}

export class RecipeUpdateRequestInput implements IRecipeUpdateRequestInput {
  name?: string;
  source?: string;
  description?: string;
  inspiredByRecipeID?: string;
  sealOfApproval?: boolean = false;
  yieldsPortions?: number;
  portionName?: string;
  pluralPortionName?: string;

  constructor(input: Partial<RecipeUpdateRequestInput> = {}) {
    this.name = input.name;
    this.source = input.source;
    this.description = input.description;
    this.inspiredByRecipeID = input.inspiredByRecipeID;
    this.sealOfApproval = input.sealOfApproval ?? false;
    this.yieldsPortions = input.yieldsPortions;
    this.portionName = input.portionName;
    this.pluralPortionName = input.pluralPortionName;
  }
}
