// Code generated by gen_typescript. DO NOT EDIT.

import { ValidInstrument } from './validInstruments';

export interface IRecipeStepVessel {
  createdAt: NonNullable<string>;
  instrument?: ValidInstrument;
  lastUpdatedAt?: string;
  archivedAt?: string;
  recipeStepProductID?: string;
  name: NonNullable<string>;
  id: NonNullable<string>;
  notes: NonNullable<string>;
  belongsToRecipeStep: NonNullable<string>;
  vesselPredicate: NonNullable<string>;
  maximumQuantity: NonNullable<number>;
  minimumQuantity: NonNullable<number>;
  unavailableAfterStep: NonNullable<boolean>;
}

export class RecipeStepVessel implements IRecipeStepVessel {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  instrument?: ValidInstrument;
  lastUpdatedAt?: string;
  archivedAt?: string;
  recipeStepProductID?: string;
  name: NonNullable<string> = '';
  id: NonNullable<string> = '';
  notes: NonNullable<string> = '';
  belongsToRecipeStep: NonNullable<string> = '';
  vesselPredicate: NonNullable<string> = '';
  maximumQuantity: NonNullable<number> = 0;
  minimumQuantity: NonNullable<number> = 0;
  unavailableAfterStep: NonNullable<boolean> = false;

  constructor(input: Partial<RecipeStepVessel> = {}) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.instrument = input.instrument;
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.archivedAt = input.archivedAt;
    this.recipeStepProductID = input.recipeStepProductID;
    this.name = input.name ?? '';
    this.id = input.id ?? '';
    this.notes = input.notes ?? '';
    this.belongsToRecipeStep = input.belongsToRecipeStep ?? '';
    this.vesselPredicate = input.vesselPredicate ?? '';
    this.maximumQuantity = input.maximumQuantity ?? 0;
    this.minimumQuantity = input.minimumQuantity ?? 0;
    this.unavailableAfterStep = input.unavailableAfterStep ?? false;
  }
}

export interface IRecipeStepVesselCreationRequestInput {
  recipeStepProductID?: string;
  productOfRecipeStepIndex?: number;
  productOfRecipeStepProductIndex?: number;
  instrumentID?: string;
  name: NonNullable<string>;
  notes: NonNullable<string>;
  vesselPredicate: NonNullable<string>;
  minimumQuantity: NonNullable<number>;
  maximumQuantity: NonNullable<number>;
  unavailableAfterStep: NonNullable<boolean>;
}

export class RecipeStepVesselCreationRequestInput implements IRecipeStepVesselCreationRequestInput {
  recipeStepProductID?: string;
  productOfRecipeStepIndex?: number;
  productOfRecipeStepProductIndex?: number;
  instrumentID?: string;
  name: NonNullable<string> = '';
  notes: NonNullable<string> = '';
  vesselPredicate: NonNullable<string> = '';
  minimumQuantity: NonNullable<number> = 0;
  maximumQuantity: NonNullable<number> = 0;
  unavailableAfterStep: NonNullable<boolean> = false;

  constructor(input: Partial<RecipeStepVesselCreationRequestInput> = {}) {
    this.recipeStepProductID = input.recipeStepProductID;
    this.productOfRecipeStepIndex = input.productOfRecipeStepIndex;
    this.productOfRecipeStepProductIndex = input.productOfRecipeStepProductIndex;
    this.instrumentID = input.instrumentID;
    this.name = input.name ?? '';
    this.notes = input.notes ?? '';
    this.vesselPredicate = input.vesselPredicate ?? '';
    this.minimumQuantity = input.minimumQuantity ?? 0;
    this.maximumQuantity = input.maximumQuantity ?? 0;
    this.unavailableAfterStep = input.unavailableAfterStep ?? false;
  }
}

export interface IRecipeStepVesselUpdateRequestInput {
  recipeStepProductID?: string;
  name?: string;
  notes?: string;
  belongsToRecipeStep?: string;
  instrumentID?: string;
  minimumQuantity?: number;
  maximumQuantity?: number;
  vesselPredicate?: string;
  unavailableAfterStep?: boolean;
}

export class RecipeStepVesselUpdateRequestInput implements IRecipeStepVesselUpdateRequestInput {
  recipeStepProductID?: string;
  name?: string;
  notes?: string;
  belongsToRecipeStep?: string;
  instrumentID?: string;
  minimumQuantity?: number;
  maximumQuantity?: number;
  vesselPredicate?: string;
  unavailableAfterStep?: boolean = false;

  constructor(input: Partial<RecipeStepVesselUpdateRequestInput> = {}) {
    this.recipeStepProductID = input.recipeStepProductID;
    this.name = input.name;
    this.notes = input.notes;
    this.belongsToRecipeStep = input.belongsToRecipeStep;
    this.instrumentID = input.instrumentID;
    this.minimumQuantity = input.minimumQuantity;
    this.maximumQuantity = input.maximumQuantity;
    this.vesselPredicate = input.vesselPredicate;
    this.unavailableAfterStep = input.unavailableAfterStep ?? false;
  }
}
