// Code generated by gen_typescript. DO NOT EDIT.

import { ValidIngredient } from './validIngredients';
import { ValidMeasurementUnit } from './validMeasurementUnits';
import { RecipeStepProductCreationRequestInput } from './recipeStepProducts';

export interface IRecipeStepIngredient {
  createdAt: NonNullable<string>;
  recipeStepProductID?: string;
  archivedAt?: string;
  ingredient?: ValidIngredient;
  lastUpdatedAt?: string;
  belongsToRecipeStep: NonNullable<string>;
  quantityNotes: NonNullable<string>;
  name: NonNullable<string>;
  id: NonNullable<string>;
  ingredientNotes: NonNullable<string>;
  measurementUnit: NonNullable<ValidMeasurementUnit>;
  minimumQuantity: NonNullable<number>;
  maximumQuantity: NonNullable<number>;
  optionIndex: NonNullable<number>;
  requiresDefrost: NonNullable<boolean>;
  optional: NonNullable<boolean>;
  productOfRecipeStep: NonNullable<boolean>;
}

export class RecipeStepIngredient implements IRecipeStepIngredient {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  recipeStepProductID?: string;
  archivedAt?: string;
  ingredient?: ValidIngredient = new ValidIngredient();
  lastUpdatedAt?: string;
  belongsToRecipeStep: NonNullable<string> = '';
  quantityNotes: NonNullable<string> = '';
  name: NonNullable<string> = '';
  id: NonNullable<string> = '';
  ingredientNotes: NonNullable<string> = '';
  measurementUnit: NonNullable<ValidMeasurementUnit> = new ValidMeasurementUnit();
  minimumQuantity: NonNullable<number> = -1;
  maximumQuantity: NonNullable<number> = -1;
  optionIndex: NonNullable<number> = -1;
  requiresDefrost: NonNullable<boolean> = false;
  optional: NonNullable<boolean> = false;
  productOfRecipeStep: NonNullable<boolean> = false;

  constructor(
    input: {
      createdAt?: string;
      recipeStepProductID?: string;
      archivedAt?: string;
      ingredient?: ValidIngredient;
      lastUpdatedAt?: string;
      belongsToRecipeStep?: string;
      quantityNotes?: string;
      name?: string;
      id?: string;
      ingredientNotes?: string;
      measurementUnit?: ValidMeasurementUnit;
      minimumQuantity?: number;
      maximumQuantity?: number;
      optionIndex?: number;
      requiresDefrost?: boolean;
      optional?: boolean;
      productOfRecipeStep?: boolean;
    } = {},
  ) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.recipeStepProductID = input.recipeStepProductID;
    this.archivedAt = input.archivedAt;
    this.ingredient = input.ingredient ?? new ValidIngredient();
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.belongsToRecipeStep = input.belongsToRecipeStep ?? '';
    this.quantityNotes = input.quantityNotes ?? '';
    this.name = input.name ?? '';
    this.id = input.id ?? '';
    this.ingredientNotes = input.ingredientNotes ?? '';
    this.measurementUnit = input.measurementUnit ?? new ValidMeasurementUnit();
    this.minimumQuantity = input.minimumQuantity ?? -1;
    this.maximumQuantity = input.maximumQuantity ?? -1;
    this.optionIndex = input.optionIndex ?? -1;
    this.requiresDefrost = input.requiresDefrost ?? false;
    this.optional = input.optional ?? false;
    this.productOfRecipeStep = input.productOfRecipeStep ?? false;
  }
}

export interface IRecipeStepIngredientCreationRequestInput {
  ingredientID?: string;
  recipeStepProduct?: RecipeStepProductCreationRequestInput;
  name: NonNullable<string>;
  measurementUnitID: NonNullable<string>;
  quantityNotes: NonNullable<string>;
  ingredientNotes: NonNullable<string>;
  maximumQuantity: NonNullable<number>;
  minimumQuantity: NonNullable<number>;
  optionIndex: NonNullable<number>;
  requiresDefrost: NonNullable<boolean>;
  optional: NonNullable<boolean>;
  productOfRecipeStep: NonNullable<boolean>;
}

export class RecipeStepIngredientCreationRequestInput implements IRecipeStepIngredientCreationRequestInput {
  ingredientID?: string;
  recipeStepProduct?: RecipeStepProductCreationRequestInput = new RecipeStepProductCreationRequestInput();
  name: NonNullable<string> = '';
  measurementUnitID: NonNullable<string> = '';
  quantityNotes: NonNullable<string> = '';
  ingredientNotes: NonNullable<string> = '';
  maximumQuantity: NonNullable<number> = -1;
  minimumQuantity: NonNullable<number> = -1;
  optionIndex: NonNullable<number> = -1;
  requiresDefrost: NonNullable<boolean> = false;
  optional: NonNullable<boolean> = false;
  productOfRecipeStep: NonNullable<boolean> = false;

  constructor(
    input: {
      ingredientID?: string;
      recipeStepProduct?: RecipeStepProductCreationRequestInput;
      name?: string;
      measurementUnitID?: string;
      quantityNotes?: string;
      ingredientNotes?: string;
      maximumQuantity?: number;
      minimumQuantity?: number;
      optionIndex?: number;
      requiresDefrost?: boolean;
      optional?: boolean;
      productOfRecipeStep?: boolean;
    } = {},
  ) {
    this.ingredientID = input.ingredientID;
    this.recipeStepProduct = input.recipeStepProduct ?? new RecipeStepProductCreationRequestInput();
    this.name = input.name ?? '';
    this.measurementUnitID = input.measurementUnitID ?? '';
    this.quantityNotes = input.quantityNotes ?? '';
    this.ingredientNotes = input.ingredientNotes ?? '';
    this.maximumQuantity = input.maximumQuantity ?? -1;
    this.minimumQuantity = input.minimumQuantity ?? -1;
    this.optionIndex = input.optionIndex ?? -1;
    this.requiresDefrost = input.requiresDefrost ?? false;
    this.optional = input.optional ?? false;
    this.productOfRecipeStep = input.productOfRecipeStep ?? false;
  }
}

export interface IRecipeStepIngredientUpdateRequestInput {
  ingredientID?: string;
  recipeStepProductID?: string;
  name?: string;
  optional?: boolean;
  measurementUnitID?: string;
  quantityNotes?: string;
  ingredientNotes?: string;
  belongsToRecipeStep?: string;
  minimumQuantity?: number;
  maximumQuantity?: number;
  productOfRecipeStep?: boolean;
  optionIndex?: number;
  requiresDefrost?: boolean;
}

export class RecipeStepIngredientUpdateRequestInput implements IRecipeStepIngredientUpdateRequestInput {
  ingredientID?: string;
  recipeStepProductID?: string;
  name?: string;
  optional?: boolean = false;
  measurementUnitID?: string;
  quantityNotes?: string;
  ingredientNotes?: string;
  belongsToRecipeStep?: string;
  minimumQuantity?: number;
  maximumQuantity?: number;
  productOfRecipeStep?: boolean = false;
  optionIndex?: number;
  requiresDefrost?: boolean = false;

  constructor(
    input: {
      ingredientID?: string;
      recipeStepProductID?: string;
      name?: string;
      optional?: boolean;
      measurementUnitID?: string;
      quantityNotes?: string;
      ingredientNotes?: string;
      belongsToRecipeStep?: string;
      minimumQuantity?: number;
      maximumQuantity?: number;
      productOfRecipeStep?: boolean;
      optionIndex?: number;
      requiresDefrost?: boolean;
    } = {},
  ) {
    this.ingredientID = input.ingredientID;
    this.recipeStepProductID = input.recipeStepProductID;
    this.name = input.name;
    this.optional = input.optional ?? false;
    this.measurementUnitID = input.measurementUnitID;
    this.quantityNotes = input.quantityNotes;
    this.ingredientNotes = input.ingredientNotes;
    this.belongsToRecipeStep = input.belongsToRecipeStep;
    this.minimumQuantity = input.minimumQuantity;
    this.maximumQuantity = input.maximumQuantity;
    this.productOfRecipeStep = input.productOfRecipeStep ?? false;
    this.optionIndex = input.optionIndex;
    this.requiresDefrost = input.requiresDefrost ?? false;
  }
}
