// Code generated by gen_typescript. DO NOT EDIT.

import { ValidIngredient } from './validIngredients';
import { ValidMeasurementUnit } from './validMeasurementUnits';

export interface IRecipeStepIngredient {
  createdAt: NonNullable<string>;
  recipeStepProductID?: string;
  archivedAt?: string;
  ingredient?: ValidIngredient;
  lastUpdatedAt?: string;
  maximumQuantity?: number;
  vesselIndex?: number;
  productPercentageToUse?: number;
  quantityNotes: NonNullable<string>;
  name: NonNullable<string>;
  id: NonNullable<string>;
  belongsToRecipeStep: NonNullable<string>;
  ingredientNotes: NonNullable<string>;
  measurementUnit: NonNullable<ValidMeasurementUnit>;
  minimumQuantity: NonNullable<number>;
  optionIndex: NonNullable<number>;
  requiresDefrost: NonNullable<boolean>;
  optional: NonNullable<boolean>;
  toTaste: NonNullable<boolean>;
}

export class RecipeStepIngredient implements IRecipeStepIngredient {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  recipeStepProductID?: string;
  archivedAt?: string;
  ingredient?: ValidIngredient;
  lastUpdatedAt?: string;
  maximumQuantity?: number;
  vesselIndex?: number;
  productPercentageToUse?: number;
  quantityNotes: NonNullable<string> = '';
  name: NonNullable<string> = '';
  id: NonNullable<string> = '';
  belongsToRecipeStep: NonNullable<string> = '';
  ingredientNotes: NonNullable<string> = '';
  measurementUnit: NonNullable<ValidMeasurementUnit> = new ValidMeasurementUnit();
  minimumQuantity: NonNullable<number> = 0;
  optionIndex: NonNullable<number> = 0;
  requiresDefrost: NonNullable<boolean> = false;
  optional: NonNullable<boolean> = false;
  toTaste: NonNullable<boolean> = false;

  constructor(input: Partial<RecipeStepIngredient> = {}) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.recipeStepProductID = input.recipeStepProductID;
    this.archivedAt = input.archivedAt;
    this.ingredient = input.ingredient;
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.maximumQuantity = input.maximumQuantity;
    this.vesselIndex = input.vesselIndex;
    this.productPercentageToUse = input.productPercentageToUse;
    this.quantityNotes = input.quantityNotes ?? '';
    this.name = input.name ?? '';
    this.id = input.id ?? '';
    this.belongsToRecipeStep = input.belongsToRecipeStep ?? '';
    this.ingredientNotes = input.ingredientNotes ?? '';
    this.measurementUnit = input.measurementUnit ?? new ValidMeasurementUnit();
    this.minimumQuantity = input.minimumQuantity ?? 0;
    this.optionIndex = input.optionIndex ?? 0;
    this.requiresDefrost = input.requiresDefrost ?? false;
    this.optional = input.optional ?? false;
    this.toTaste = input.toTaste ?? false;
  }
}

export interface IRecipeStepIngredientCreationRequestInput {
  ingredientID?: string;
  productOfRecipeStepIndex?: number;
  productOfRecipeStepProductIndex?: number;
  maximumQuantity?: number;
  vesselIndex?: number;
  productPercentageToUse?: number;
  ingredientNotes: NonNullable<string>;
  measurementUnitID: NonNullable<string>;
  name: NonNullable<string>;
  quantityNotes: NonNullable<string>;
  minimumQuantity: NonNullable<number>;
  optionIndex: NonNullable<number>;
  requiresDefrost: NonNullable<boolean>;
  optional: NonNullable<boolean>;
  toTaste: NonNullable<boolean>;
}

export class RecipeStepIngredientCreationRequestInput implements IRecipeStepIngredientCreationRequestInput {
  ingredientID?: string;
  productOfRecipeStepIndex?: number;
  productOfRecipeStepProductIndex?: number;
  maximumQuantity?: number;
  vesselIndex?: number;
  productPercentageToUse?: number;
  ingredientNotes: NonNullable<string> = '';
  measurementUnitID: NonNullable<string> = '';
  name: NonNullable<string> = '';
  quantityNotes: NonNullable<string> = '';
  minimumQuantity: NonNullable<number> = 0;
  optionIndex: NonNullable<number> = 0;
  requiresDefrost: NonNullable<boolean> = false;
  optional: NonNullable<boolean> = false;
  toTaste: NonNullable<boolean> = false;

  constructor(input: Partial<RecipeStepIngredientCreationRequestInput> = {}) {
    this.ingredientID = input.ingredientID;
    this.productOfRecipeStepIndex = input.productOfRecipeStepIndex;
    this.productOfRecipeStepProductIndex = input.productOfRecipeStepProductIndex;
    this.maximumQuantity = input.maximumQuantity;
    this.vesselIndex = input.vesselIndex;
    this.productPercentageToUse = input.productPercentageToUse;
    this.ingredientNotes = input.ingredientNotes ?? '';
    this.measurementUnitID = input.measurementUnitID ?? '';
    this.name = input.name ?? '';
    this.quantityNotes = input.quantityNotes ?? '';
    this.minimumQuantity = input.minimumQuantity ?? 0;
    this.optionIndex = input.optionIndex ?? 0;
    this.requiresDefrost = input.requiresDefrost ?? false;
    this.optional = input.optional ?? false;
    this.toTaste = input.toTaste ?? false;
  }
}

export interface IRecipeStepIngredientUpdateRequestInput {
  ingredientID?: string;
  recipeStepProductID?: string;
  name?: string;
  optional?: boolean;
  measurementUnitID?: string;
  quantityNotes?: string;
  ingredientNotes?: string;
  belongsToRecipeStep?: string;
  minimumQuantity?: number;
  maximumQuantity?: number;
  optionIndex?: number;
  requiresDefrost?: boolean;
  vesselIndex?: number;
  toTaste?: boolean;
  productPercentageToUse?: number;
}

export class RecipeStepIngredientUpdateRequestInput implements IRecipeStepIngredientUpdateRequestInput {
  ingredientID?: string;
  recipeStepProductID?: string;
  name?: string;
  optional?: boolean = false;
  measurementUnitID?: string;
  quantityNotes?: string;
  ingredientNotes?: string;
  belongsToRecipeStep?: string;
  minimumQuantity?: number;
  maximumQuantity?: number;
  optionIndex?: number;
  requiresDefrost?: boolean = false;
  vesselIndex?: number;
  toTaste?: boolean = false;
  productPercentageToUse?: number;

  constructor(input: Partial<RecipeStepIngredientUpdateRequestInput> = {}) {
    this.ingredientID = input.ingredientID;
    this.recipeStepProductID = input.recipeStepProductID;
    this.name = input.name;
    this.optional = input.optional ?? false;
    this.measurementUnitID = input.measurementUnitID;
    this.quantityNotes = input.quantityNotes;
    this.ingredientNotes = input.ingredientNotes;
    this.belongsToRecipeStep = input.belongsToRecipeStep;
    this.minimumQuantity = input.minimumQuantity;
    this.maximumQuantity = input.maximumQuantity;
    this.optionIndex = input.optionIndex;
    this.requiresDefrost = input.requiresDefrost ?? false;
    this.vesselIndex = input.vesselIndex;
    this.toTaste = input.toTaste ?? false;
    this.productPercentageToUse = input.productPercentageToUse;
  }
}
