// Code generated by gen_typescript. DO NOT EDIT.

import { RecipeMedia } from './recipeMedia';
import {
  RecipeStepCompletionCondition,
  RecipeStepCompletionConditionCreationRequestInput,
} from './recipeStepCompletionConditions';
import { RecipeStepIngredient, RecipeStepIngredientCreationRequestInput } from './recipeStepIngredients';
import { RecipeStepInstrument, RecipeStepInstrumentCreationRequestInput } from './recipeStepInstruments';
import { RecipeStepProduct, RecipeStepProductCreationRequestInput } from './recipeStepProducts';
import { RecipeStepVessel, RecipeStepVesselCreationRequestInput } from './recipeStepVessels';
import { ValidPreparation } from './validPreparations';

export interface IRecipeStep {
  createdAt: NonNullable<string>;
  minimumEstimatedTimeInSeconds?: number;
  archivedAt?: string;
  lastUpdatedAt?: string;
  minimumTemperatureInCelsius?: number;
  maximumTemperatureInCelsius?: number;
  maximumEstimatedTimeInSeconds?: number;
  explicitInstructions: NonNullable<string>;
  notes: NonNullable<string>;
  id: NonNullable<string>;
  belongsToRecipe: NonNullable<string>;
  conditionExpression: NonNullable<string>;
  products: NonNullable<Array<RecipeStepProduct>>;
  media: NonNullable<Array<RecipeMedia>>;
  instruments: NonNullable<Array<RecipeStepInstrument>>;
  vessels: NonNullable<Array<RecipeStepVessel>>;
  completionConditions: NonNullable<Array<RecipeStepCompletionCondition>>;
  ingredients: NonNullable<Array<RecipeStepIngredient>>;
  preparation: NonNullable<ValidPreparation>;
  index: NonNullable<number>;
  optional: NonNullable<boolean>;
  startTimerAutomatically: NonNullable<boolean>;
}

export class RecipeStep implements IRecipeStep {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  minimumEstimatedTimeInSeconds?: number;
  archivedAt?: string;
  lastUpdatedAt?: string;
  minimumTemperatureInCelsius?: number;
  maximumTemperatureInCelsius?: number;
  maximumEstimatedTimeInSeconds?: number;
  explicitInstructions: NonNullable<string> = '';
  notes: NonNullable<string> = '';
  id: NonNullable<string> = '';
  belongsToRecipe: NonNullable<string> = '';
  conditionExpression: NonNullable<string> = '';
  products: NonNullable<Array<RecipeStepProduct>> = [];
  media: NonNullable<Array<RecipeMedia>> = [];
  instruments: NonNullable<Array<RecipeStepInstrument>> = [];
  vessels: NonNullable<Array<RecipeStepVessel>> = [];
  completionConditions: NonNullable<Array<RecipeStepCompletionCondition>> = [];
  ingredients: NonNullable<Array<RecipeStepIngredient>> = [];
  preparation: NonNullable<ValidPreparation> = new ValidPreparation();
  index: NonNullable<number> = 0;
  optional: NonNullable<boolean> = false;
  startTimerAutomatically: NonNullable<boolean> = false;

  constructor(input: Partial<RecipeStep> = {}) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.minimumEstimatedTimeInSeconds = input.minimumEstimatedTimeInSeconds;
    this.archivedAt = input.archivedAt;
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.minimumTemperatureInCelsius = input.minimumTemperatureInCelsius;
    this.maximumTemperatureInCelsius = input.maximumTemperatureInCelsius;
    this.maximumEstimatedTimeInSeconds = input.maximumEstimatedTimeInSeconds;
    this.explicitInstructions = input.explicitInstructions ?? '';
    this.notes = input.notes ?? '';
    this.id = input.id ?? '';
    this.belongsToRecipe = input.belongsToRecipe ?? '';
    this.conditionExpression = input.conditionExpression ?? '';
    this.products = input.products ?? [];
    this.media = input.media ?? [];
    this.instruments = input.instruments ?? [];
    this.vessels = input.vessels ?? [];
    this.completionConditions = input.completionConditions ?? [];
    this.ingredients = input.ingredients ?? [];
    this.preparation = input.preparation ?? new ValidPreparation();
    this.index = input.index ?? 0;
    this.optional = input.optional ?? false;
    this.startTimerAutomatically = input.startTimerAutomatically ?? false;
  }
}

export interface IRecipeStepCreationRequestInput {
  maximumTemperatureInCelsius?: number;
  minimumTemperatureInCelsius?: number;
  maximumEstimatedTimeInSeconds?: number;
  minimumEstimatedTimeInSeconds?: number;
  conditionExpression: NonNullable<string>;
  notes: NonNullable<string>;
  preparationID: NonNullable<string>;
  explicitInstructions: NonNullable<string>;
  instruments: NonNullable<Array<RecipeStepInstrumentCreationRequestInput>>;
  vessels: NonNullable<Array<RecipeStepVesselCreationRequestInput>>;
  products: NonNullable<Array<RecipeStepProductCreationRequestInput>>;
  ingredients: NonNullable<Array<RecipeStepIngredientCreationRequestInput>>;
  completionConditions: NonNullable<Array<RecipeStepCompletionConditionCreationRequestInput>>;
  index: NonNullable<number>;
  optional: NonNullable<boolean>;
  startTimerAutomatically: NonNullable<boolean>;
}

export class RecipeStepCreationRequestInput implements IRecipeStepCreationRequestInput {
  maximumTemperatureInCelsius?: number;
  minimumTemperatureInCelsius?: number;
  maximumEstimatedTimeInSeconds?: number;
  minimumEstimatedTimeInSeconds?: number;
  conditionExpression: NonNullable<string> = '';
  notes: NonNullable<string> = '';
  preparationID: NonNullable<string> = '';
  explicitInstructions: NonNullable<string> = '';
  instruments: NonNullable<Array<RecipeStepInstrumentCreationRequestInput>> = [];
  vessels: NonNullable<Array<RecipeStepVesselCreationRequestInput>> = [];
  products: NonNullable<Array<RecipeStepProductCreationRequestInput>> = [];
  ingredients: NonNullable<Array<RecipeStepIngredientCreationRequestInput>> = [];
  completionConditions: NonNullable<Array<RecipeStepCompletionConditionCreationRequestInput>> = [];
  index: NonNullable<number> = 0;
  optional: NonNullable<boolean> = false;
  startTimerAutomatically: NonNullable<boolean> = false;

  constructor(input: Partial<RecipeStepCreationRequestInput> = {}) {
    this.maximumTemperatureInCelsius = input.maximumTemperatureInCelsius;
    this.minimumTemperatureInCelsius = input.minimumTemperatureInCelsius;
    this.maximumEstimatedTimeInSeconds = input.maximumEstimatedTimeInSeconds;
    this.minimumEstimatedTimeInSeconds = input.minimumEstimatedTimeInSeconds;
    this.conditionExpression = input.conditionExpression ?? '';
    this.notes = input.notes ?? '';
    this.preparationID = input.preparationID ?? '';
    this.explicitInstructions = input.explicitInstructions ?? '';
    this.instruments = input.instruments ?? [];
    this.vessels = input.vessels ?? [];
    this.products = input.products ?? [];
    this.ingredients = input.ingredients ?? [];
    this.completionConditions = input.completionConditions ?? [];
    this.index = input.index ?? 0;
    this.optional = input.optional ?? false;
    this.startTimerAutomatically = input.startTimerAutomatically ?? false;
  }
}

export interface IRecipeStepUpdateRequestInput {
  minimumEstimatedTimeInSeconds?: number;
  maximumTemperatureInCelsius?: number;
  notes?: string;
  preparation?: ValidPreparation;
  index?: number;
  minimumTemperatureInCelsius?: number;
  maximumEstimatedTimeInSeconds?: number;
  optional?: boolean;
  explicitInstructions?: string;
  conditionExpression?: string;
  startTimerAutomatically?: boolean;
  belongsToRecipe: NonNullable<string>;
}

export class RecipeStepUpdateRequestInput implements IRecipeStepUpdateRequestInput {
  minimumEstimatedTimeInSeconds?: number;
  maximumTemperatureInCelsius?: number;
  notes?: string;
  preparation?: ValidPreparation;
  index?: number;
  minimumTemperatureInCelsius?: number;
  maximumEstimatedTimeInSeconds?: number;
  optional?: boolean = false;
  explicitInstructions?: string;
  conditionExpression?: string;
  startTimerAutomatically?: boolean = false;
  belongsToRecipe: NonNullable<string> = '';

  constructor(input: Partial<RecipeStepUpdateRequestInput> = {}) {
    this.minimumEstimatedTimeInSeconds = input.minimumEstimatedTimeInSeconds;
    this.maximumTemperatureInCelsius = input.maximumTemperatureInCelsius;
    this.notes = input.notes;
    this.preparation = input.preparation;
    this.index = input.index;
    this.minimumTemperatureInCelsius = input.minimumTemperatureInCelsius;
    this.maximumEstimatedTimeInSeconds = input.maximumEstimatedTimeInSeconds;
    this.optional = input.optional ?? false;
    this.explicitInstructions = input.explicitInstructions;
    this.conditionExpression = input.conditionExpression;
    this.startTimerAutomatically = input.startTimerAutomatically ?? false;
    this.belongsToRecipe = input.belongsToRecipe ?? '';
  }
}
