// Code generated by gen_typescript. DO NOT EDIT.

export interface IRecipePrepTaskStep {
  id: NonNullable<string>;
  belongsToRecipeStep: NonNullable<string>;
  belongsToRecipeStepTask: NonNullable<string>;
  satisfiesRecipeStep: NonNullable<boolean>;
}

export class RecipePrepTaskStep implements IRecipePrepTaskStep {
  id: NonNullable<string> = '';
  belongsToRecipeStep: NonNullable<string> = '';
  belongsToRecipeStepTask: NonNullable<string> = '';
  satisfiesRecipeStep: NonNullable<boolean> = false;

  constructor(
    input: {
      id?: string;
      belongsToRecipeStep?: string;
      belongsToRecipeStepTask?: string;
      satisfiesRecipeStep?: boolean;
    } = {},
  ) {
    this.id = input.id ?? '';
    this.belongsToRecipeStep = input.belongsToRecipeStep ?? '';
    this.belongsToRecipeStepTask = input.belongsToRecipeStepTask ?? '';
    this.satisfiesRecipeStep = input.satisfiesRecipeStep ?? false;
  }
}

export interface IRecipePrepTaskStepWithinRecipeCreationRequestInput {
  belongsToRecipeStepIndex: NonNullable<number>;
  satisfiesRecipeStep: NonNullable<boolean>;
}

export class RecipePrepTaskStepWithinRecipeCreationRequestInput
  implements IRecipePrepTaskStepWithinRecipeCreationRequestInput
{
  belongsToRecipeStepIndex: NonNullable<number> = -1;
  satisfiesRecipeStep: NonNullable<boolean> = false;

  constructor(
    input: {
      belongsToRecipeStepIndex?: number;
      satisfiesRecipeStep?: boolean;
    } = {},
  ) {
    this.belongsToRecipeStepIndex = input.belongsToRecipeStepIndex ?? -1;
    this.satisfiesRecipeStep = input.satisfiesRecipeStep ?? false;
  }
}

export interface IRecipePrepTaskStepCreationRequestInput {
  belongsToRecipeStep: NonNullable<string>;
  satisfiesRecipeStep: NonNullable<boolean>;
}

export class RecipePrepTaskStepCreationRequestInput implements IRecipePrepTaskStepCreationRequestInput {
  belongsToRecipeStep: NonNullable<string> = '';
  satisfiesRecipeStep: NonNullable<boolean> = false;

  constructor(
    input: {
      belongsToRecipeStep?: string;
      satisfiesRecipeStep?: boolean;
    } = {},
  ) {
    this.belongsToRecipeStep = input.belongsToRecipeStep ?? '';
    this.satisfiesRecipeStep = input.satisfiesRecipeStep ?? false;
  }
}

export interface IRecipePrepTaskStepUpdateRequestInput {
  satisfiesRecipeStep?: boolean;
  belongsToRecipeStep?: string;
  belongsToRecipeStepTask?: string;
}

export class RecipePrepTaskStepUpdateRequestInput implements IRecipePrepTaskStepUpdateRequestInput {
  satisfiesRecipeStep?: boolean = false;
  belongsToRecipeStep?: string;
  belongsToRecipeStepTask?: string;

  constructor(
    input: {
      satisfiesRecipeStep?: boolean;
      belongsToRecipeStep?: string;
      belongsToRecipeStepTask?: string;
    } = {},
  ) {
    this.satisfiesRecipeStep = input.satisfiesRecipeStep ?? false;
    this.belongsToRecipeStep = input.belongsToRecipeStep;
    this.belongsToRecipeStepTask = input.belongsToRecipeStepTask;
  }
}
