// Code generated by gen_typescript. DO NOT EDIT.

import { RecipeMedia } from './recipeMedia';
import {
  RecipeStepCompletionCondition,
  RecipeStepCompletionConditionCreationRequestInput,
} from './recipeStepCompletionConditions';
import { RecipeStepIngredient, RecipeStepIngredientCreationRequestInput } from './recipeStepIngredients';
import { RecipeStepInstrument, RecipeStepInstrumentCreationRequestInput } from './recipeStepInstruments';
import { RecipeStepProduct, RecipeStepProductCreationRequestInput } from './recipeStepProducts';
import { ValidPreparation } from './validPreparations';

export interface IRecipeStep {
  createdAt: NonNullable<string>;
  maximumTemperatureInCelsius?: number;
  minimumEstimatedTimeInSeconds?: number;
  maximumEstimatedTimeInSeconds?: number;
  minimumTemperatureInCelsius?: number;
  lastUpdatedAt?: string;
  archivedAt?: string;
  conditionExpression: NonNullable<string>;
  id: NonNullable<string>;
  notes: NonNullable<string>;
  belongsToRecipe: NonNullable<string>;
  explicitInstructions: NonNullable<string>;
  ingredients: NonNullable<Array<RecipeStepIngredient>>;
  products: NonNullable<Array<RecipeStepProduct>>;
  media: NonNullable<Array<RecipeMedia>>;
  instruments: NonNullable<Array<RecipeStepInstrument>>;
  completionConditions: NonNullable<Array<RecipeStepCompletionCondition>>;
  preparation: NonNullable<ValidPreparation>;
  index: NonNullable<number>;
  optional: NonNullable<boolean>;
}

export class RecipeStep implements IRecipeStep {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  maximumTemperatureInCelsius?: number;
  minimumEstimatedTimeInSeconds?: number;
  maximumEstimatedTimeInSeconds?: number;
  minimumTemperatureInCelsius?: number;
  lastUpdatedAt?: string;
  archivedAt?: string;
  conditionExpression: NonNullable<string> = '';
  id: NonNullable<string> = '';
  notes: NonNullable<string> = '';
  belongsToRecipe: NonNullable<string> = '';
  explicitInstructions: NonNullable<string> = '';
  ingredients: NonNullable<Array<RecipeStepIngredient>> = [];
  products: NonNullable<Array<RecipeStepProduct>> = [];
  media: NonNullable<Array<RecipeMedia>> = [];
  instruments: NonNullable<Array<RecipeStepInstrument>> = [];
  completionConditions: NonNullable<Array<RecipeStepCompletionCondition>> = [];
  preparation: NonNullable<ValidPreparation> = new ValidPreparation();
  index: NonNullable<number> = 0;
  optional: NonNullable<boolean> = false;

  constructor(
    input: {
      createdAt?: string;
      maximumTemperatureInCelsius?: number;
      minimumEstimatedTimeInSeconds?: number;
      maximumEstimatedTimeInSeconds?: number;
      minimumTemperatureInCelsius?: number;
      lastUpdatedAt?: string;
      archivedAt?: string;
      conditionExpression?: string;
      id?: string;
      notes?: string;
      belongsToRecipe?: string;
      explicitInstructions?: string;
      ingredients?: RecipeStepIngredient[];
      products?: RecipeStepProduct[];
      media?: RecipeMedia[];
      instruments?: RecipeStepInstrument[];
      completionConditions?: RecipeStepCompletionCondition[];
      preparation?: ValidPreparation;
      index?: number;
      optional?: boolean;
    } = {},
  ) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.maximumTemperatureInCelsius = input.maximumTemperatureInCelsius;
    this.minimumEstimatedTimeInSeconds = input.minimumEstimatedTimeInSeconds;
    this.maximumEstimatedTimeInSeconds = input.maximumEstimatedTimeInSeconds;
    this.minimumTemperatureInCelsius = input.minimumTemperatureInCelsius;
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.archivedAt = input.archivedAt;
    this.conditionExpression = input.conditionExpression ?? '';
    this.id = input.id ?? '';
    this.notes = input.notes ?? '';
    this.belongsToRecipe = input.belongsToRecipe ?? '';
    this.explicitInstructions = input.explicitInstructions ?? '';
    this.ingredients = input.ingredients ?? [];
    this.products = input.products ?? [];
    this.media = input.media ?? [];
    this.instruments = input.instruments ?? [];
    this.completionConditions = input.completionConditions ?? [];
    this.preparation = input.preparation ?? new ValidPreparation();
    this.index = input.index ?? 0;
    this.optional = input.optional ?? false;
  }
}

export interface IRecipeStepCreationRequestInput {
  maximumTemperatureInCelsius?: number;
  minimumTemperatureInCelsius?: number;
  maximumEstimatedTimeInSeconds?: number;
  minimumEstimatedTimeInSeconds?: number;
  conditionExpression: NonNullable<string>;
  notes: NonNullable<string>;
  preparationID: NonNullable<string>;
  explicitInstructions: NonNullable<string>;
  instruments: NonNullable<Array<RecipeStepInstrumentCreationRequestInput>>;
  products: NonNullable<Array<RecipeStepProductCreationRequestInput>>;
  ingredients: NonNullable<Array<RecipeStepIngredientCreationRequestInput>>;
  completionConditions: NonNullable<Array<RecipeStepCompletionConditionCreationRequestInput>>;
  index: NonNullable<number>;
  optional: NonNullable<boolean>;
}

export class RecipeStepCreationRequestInput implements IRecipeStepCreationRequestInput {
  maximumTemperatureInCelsius?: number;
  minimumTemperatureInCelsius?: number;
  maximumEstimatedTimeInSeconds?: number;
  minimumEstimatedTimeInSeconds?: number;
  conditionExpression: NonNullable<string> = '';
  notes: NonNullable<string> = '';
  preparationID: NonNullable<string> = '';
  explicitInstructions: NonNullable<string> = '';
  instruments: NonNullable<Array<RecipeStepInstrumentCreationRequestInput>> = [];
  products: NonNullable<Array<RecipeStepProductCreationRequestInput>> = [];
  ingredients: NonNullable<Array<RecipeStepIngredientCreationRequestInput>> = [];
  completionConditions: NonNullable<Array<RecipeStepCompletionConditionCreationRequestInput>> = [];
  index: NonNullable<number> = 0;
  optional: NonNullable<boolean> = false;

  constructor(
    input: {
      maximumTemperatureInCelsius?: number;
      minimumTemperatureInCelsius?: number;
      maximumEstimatedTimeInSeconds?: number;
      minimumEstimatedTimeInSeconds?: number;
      conditionExpression?: string;
      notes?: string;
      preparationID?: string;
      explicitInstructions?: string;
      instruments?: RecipeStepInstrumentCreationRequestInput[];
      products?: RecipeStepProductCreationRequestInput[];
      ingredients?: RecipeStepIngredientCreationRequestInput[];
      completionConditions?: RecipeStepCompletionConditionCreationRequestInput[];
      index?: number;
      optional?: boolean;
    } = {},
  ) {
    this.maximumTemperatureInCelsius = input.maximumTemperatureInCelsius;
    this.minimumTemperatureInCelsius = input.minimumTemperatureInCelsius;
    this.maximumEstimatedTimeInSeconds = input.maximumEstimatedTimeInSeconds;
    this.minimumEstimatedTimeInSeconds = input.minimumEstimatedTimeInSeconds;
    this.conditionExpression = input.conditionExpression ?? '';
    this.notes = input.notes ?? '';
    this.preparationID = input.preparationID ?? '';
    this.explicitInstructions = input.explicitInstructions ?? '';
    this.instruments = input.instruments ?? [];
    this.products = input.products ?? [];
    this.ingredients = input.ingredients ?? [];
    this.completionConditions = input.completionConditions ?? [];
    this.index = input.index ?? 0;
    this.optional = input.optional ?? false;
  }
}

export interface IRecipeStepUpdateRequestInput {
  minimumTemperatureInCelsius?: number;
  maximumTemperatureInCelsius?: number;
  notes?: string;
  preparation?: ValidPreparation;
  index?: number;
  minimumEstimatedTimeInSeconds?: number;
  maximumEstimatedTimeInSeconds?: number;
  optional?: boolean;
  explicitInstructions?: string;
  conditionExpression?: string;
  belongsToRecipe: NonNullable<string>;
}

export class RecipeStepUpdateRequestInput implements IRecipeStepUpdateRequestInput {
  minimumTemperatureInCelsius?: number;
  maximumTemperatureInCelsius?: number;
  notes?: string;
  preparation?: ValidPreparation = new ValidPreparation();
  index?: number;
  minimumEstimatedTimeInSeconds?: number;
  maximumEstimatedTimeInSeconds?: number;
  optional?: boolean = false;
  explicitInstructions?: string;
  conditionExpression?: string;
  belongsToRecipe: NonNullable<string> = '';

  constructor(
    input: {
      minimumTemperatureInCelsius?: number;
      maximumTemperatureInCelsius?: number;
      notes?: string;
      preparation?: ValidPreparation;
      index?: number;
      minimumEstimatedTimeInSeconds?: number;
      maximumEstimatedTimeInSeconds?: number;
      optional?: boolean;
      explicitInstructions?: string;
      conditionExpression?: string;
      belongsToRecipe?: string;
    } = {},
  ) {
    this.minimumTemperatureInCelsius = input.minimumTemperatureInCelsius;
    this.maximumTemperatureInCelsius = input.maximumTemperatureInCelsius;
    this.notes = input.notes;
    this.preparation = input.preparation ?? new ValidPreparation();
    this.index = input.index;
    this.minimumEstimatedTimeInSeconds = input.minimumEstimatedTimeInSeconds;
    this.maximumEstimatedTimeInSeconds = input.maximumEstimatedTimeInSeconds;
    this.optional = input.optional ?? false;
    this.explicitInstructions = input.explicitInstructions;
    this.conditionExpression = input.conditionExpression;
    this.belongsToRecipe = input.belongsToRecipe ?? '';
  }
}
