// Code generated by gen_typescript. DO NOT EDIT.

import {
  RecipePrepTaskStep,
  RecipePrepTaskStepCreationRequestInput,
  RecipePrepTaskStepUpdateRequestInput,
  RecipePrepTaskStepWithinRecipeCreationRequestInput,
} from './recipePrepTaskSteps';

export interface IRecipePrepTask {
  createdAt: NonNullable<string>;
  archivedAt?: string;
  lastUpdatedAt?: string;
  notes: NonNullable<string>;
  explicitStorageInstructions: NonNullable<string>;
  storageType: NonNullable<string>;
  belongsToRecipe: NonNullable<string>;
  id: NonNullable<string>;
  recipeSteps: NonNullable<Array<RecipePrepTaskStep>>;
  minimumTimeBufferBeforeRecipeInSeconds: NonNullable<number>;
  maximumStorageTemperatureInCelsius: NonNullable<number>;
  maximumTimeBufferBeforeRecipeInSeconds: NonNullable<number>;
  minimumStorageTemperatureInCelsius: NonNullable<number>;
}

export class RecipePrepTask implements IRecipePrepTask {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  archivedAt?: string;
  lastUpdatedAt?: string;
  notes: NonNullable<string> = '';
  explicitStorageInstructions: NonNullable<string> = '';
  storageType: NonNullable<string> = '';
  belongsToRecipe: NonNullable<string> = '';
  id: NonNullable<string> = '';
  recipeSteps: NonNullable<Array<RecipePrepTaskStep>> = [];
  minimumTimeBufferBeforeRecipeInSeconds: NonNullable<number> = -1;
  maximumStorageTemperatureInCelsius: NonNullable<number> = -1;
  maximumTimeBufferBeforeRecipeInSeconds: NonNullable<number> = -1;
  minimumStorageTemperatureInCelsius: NonNullable<number> = -1;

  constructor(
    input: {
      createdAt?: string;
      archivedAt?: string;
      lastUpdatedAt?: string;
      notes?: string;
      explicitStorageInstructions?: string;
      storageType?: string;
      belongsToRecipe?: string;
      id?: string;
      recipeSteps?: RecipePrepTaskStep[];
      minimumTimeBufferBeforeRecipeInSeconds?: number;
      maximumStorageTemperatureInCelsius?: number;
      maximumTimeBufferBeforeRecipeInSeconds?: number;
      minimumStorageTemperatureInCelsius?: number;
    } = {},
  ) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.archivedAt = input.archivedAt;
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.notes = input.notes ?? '';
    this.explicitStorageInstructions = input.explicitStorageInstructions ?? '';
    this.storageType = input.storageType ?? '';
    this.belongsToRecipe = input.belongsToRecipe ?? '';
    this.id = input.id ?? '';
    this.recipeSteps = input.recipeSteps ?? [];
    this.minimumTimeBufferBeforeRecipeInSeconds = input.minimumTimeBufferBeforeRecipeInSeconds ?? -1;
    this.maximumStorageTemperatureInCelsius = input.maximumStorageTemperatureInCelsius ?? -1;
    this.maximumTimeBufferBeforeRecipeInSeconds = input.maximumTimeBufferBeforeRecipeInSeconds ?? -1;
    this.minimumStorageTemperatureInCelsius = input.minimumStorageTemperatureInCelsius ?? -1;
  }
}

export interface IRecipePrepTaskCreationRequestInput {
  notes: NonNullable<string>;
  explicitStorageInstructions: NonNullable<string>;
  storageType: NonNullable<string>;
  belongsToRecipe: NonNullable<string>;
  recipeSteps: NonNullable<Array<RecipePrepTaskStepCreationRequestInput>>;
  maximumTimeBufferBeforeRecipeInSeconds: NonNullable<number>;
  minimumStorageTemperatureInCelsius: NonNullable<number>;
  maximumStorageTemperatureInCelsius: NonNullable<number>;
  minimumTimeBufferBeforeRecipeInSeconds: NonNullable<number>;
}

export class RecipePrepTaskCreationRequestInput implements IRecipePrepTaskCreationRequestInput {
  notes: NonNullable<string> = '';
  explicitStorageInstructions: NonNullable<string> = '';
  storageType: NonNullable<string> = '';
  belongsToRecipe: NonNullable<string> = '';
  recipeSteps: NonNullable<Array<RecipePrepTaskStepCreationRequestInput>> = [];
  maximumTimeBufferBeforeRecipeInSeconds: NonNullable<number> = -1;
  minimumStorageTemperatureInCelsius: NonNullable<number> = -1;
  maximumStorageTemperatureInCelsius: NonNullable<number> = -1;
  minimumTimeBufferBeforeRecipeInSeconds: NonNullable<number> = -1;

  constructor(
    input: {
      notes?: string;
      explicitStorageInstructions?: string;
      storageType?: string;
      belongsToRecipe?: string;
      recipeSteps?: RecipePrepTaskStepCreationRequestInput[];
      maximumTimeBufferBeforeRecipeInSeconds?: number;
      minimumStorageTemperatureInCelsius?: number;
      maximumStorageTemperatureInCelsius?: number;
      minimumTimeBufferBeforeRecipeInSeconds?: number;
    } = {},
  ) {
    this.notes = input.notes ?? '';
    this.explicitStorageInstructions = input.explicitStorageInstructions ?? '';
    this.storageType = input.storageType ?? '';
    this.belongsToRecipe = input.belongsToRecipe ?? '';
    this.recipeSteps = input.recipeSteps ?? [];
    this.maximumTimeBufferBeforeRecipeInSeconds = input.maximumTimeBufferBeforeRecipeInSeconds ?? -1;
    this.minimumStorageTemperatureInCelsius = input.minimumStorageTemperatureInCelsius ?? -1;
    this.maximumStorageTemperatureInCelsius = input.maximumStorageTemperatureInCelsius ?? -1;
    this.minimumTimeBufferBeforeRecipeInSeconds = input.minimumTimeBufferBeforeRecipeInSeconds ?? -1;
  }
}

export interface IRecipePrepTaskWithinRecipeCreationRequestInput {
  notes: NonNullable<string>;
  explicitStorageInstructions: NonNullable<string>;
  storageType: NonNullable<string>;
  belongsToRecipe: NonNullable<string>;
  recipeSteps: NonNullable<Array<RecipePrepTaskStepWithinRecipeCreationRequestInput>>;
  maximumTimeBufferBeforeRecipeInSeconds: NonNullable<number>;
  minimumStorageTemperatureInCelsius: NonNullable<number>;
  maximumStorageTemperatureInCelsius: NonNullable<number>;
  minimumTimeBufferBeforeRecipeInSeconds: NonNullable<number>;
}

export class RecipePrepTaskWithinRecipeCreationRequestInput implements IRecipePrepTaskWithinRecipeCreationRequestInput {
  notes: NonNullable<string> = '';
  explicitStorageInstructions: NonNullable<string> = '';
  storageType: NonNullable<string> = '';
  belongsToRecipe: NonNullable<string> = '';
  recipeSteps: NonNullable<Array<RecipePrepTaskStepWithinRecipeCreationRequestInput>> = [];
  maximumTimeBufferBeforeRecipeInSeconds: NonNullable<number> = -1;
  minimumStorageTemperatureInCelsius: NonNullable<number> = -1;
  maximumStorageTemperatureInCelsius: NonNullable<number> = -1;
  minimumTimeBufferBeforeRecipeInSeconds: NonNullable<number> = -1;

  constructor(
    input: {
      notes?: string;
      explicitStorageInstructions?: string;
      storageType?: string;
      belongsToRecipe?: string;
      recipeSteps?: RecipePrepTaskStepWithinRecipeCreationRequestInput[];
      maximumTimeBufferBeforeRecipeInSeconds?: number;
      minimumStorageTemperatureInCelsius?: number;
      maximumStorageTemperatureInCelsius?: number;
      minimumTimeBufferBeforeRecipeInSeconds?: number;
    } = {},
  ) {
    this.notes = input.notes ?? '';
    this.explicitStorageInstructions = input.explicitStorageInstructions ?? '';
    this.storageType = input.storageType ?? '';
    this.belongsToRecipe = input.belongsToRecipe ?? '';
    this.recipeSteps = input.recipeSteps ?? [];
    this.maximumTimeBufferBeforeRecipeInSeconds = input.maximumTimeBufferBeforeRecipeInSeconds ?? -1;
    this.minimumStorageTemperatureInCelsius = input.minimumStorageTemperatureInCelsius ?? -1;
    this.maximumStorageTemperatureInCelsius = input.maximumStorageTemperatureInCelsius ?? -1;
    this.minimumTimeBufferBeforeRecipeInSeconds = input.minimumTimeBufferBeforeRecipeInSeconds ?? -1;
  }
}

export interface IRecipePrepTaskUpdateRequestInput {
  notes?: string;
  explicitStorageInstructions?: string;
  minimumTimeBufferBeforeRecipeInSeconds?: number;
  maximumTimeBufferBeforeRecipeInSeconds?: number;
  storageType?: string;
  minimumStorageTemperatureInCelsius?: number;
  maximumStorageTemperatureInCelsius?: number;
  belongsToRecipe?: string;
  recipeSteps: NonNullable<Array<RecipePrepTaskStepUpdateRequestInput>>;
}

export class RecipePrepTaskUpdateRequestInput implements IRecipePrepTaskUpdateRequestInput {
  notes?: string;
  explicitStorageInstructions?: string;
  minimumTimeBufferBeforeRecipeInSeconds?: number;
  maximumTimeBufferBeforeRecipeInSeconds?: number;
  storageType?: string;
  minimumStorageTemperatureInCelsius?: number;
  maximumStorageTemperatureInCelsius?: number;
  belongsToRecipe?: string;
  recipeSteps: NonNullable<Array<RecipePrepTaskStepUpdateRequestInput>> = [];

  constructor(
    input: {
      notes?: string;
      explicitStorageInstructions?: string;
      minimumTimeBufferBeforeRecipeInSeconds?: number;
      maximumTimeBufferBeforeRecipeInSeconds?: number;
      storageType?: string;
      minimumStorageTemperatureInCelsius?: number;
      maximumStorageTemperatureInCelsius?: number;
      belongsToRecipe?: string;
      recipeSteps?: RecipePrepTaskStepUpdateRequestInput[];
    } = {},
  ) {
    this.notes = input.notes;
    this.explicitStorageInstructions = input.explicitStorageInstructions;
    this.minimumTimeBufferBeforeRecipeInSeconds = input.minimumTimeBufferBeforeRecipeInSeconds;
    this.maximumTimeBufferBeforeRecipeInSeconds = input.maximumTimeBufferBeforeRecipeInSeconds;
    this.storageType = input.storageType;
    this.minimumStorageTemperatureInCelsius = input.minimumStorageTemperatureInCelsius;
    this.maximumStorageTemperatureInCelsius = input.maximumStorageTemperatureInCelsius;
    this.belongsToRecipe = input.belongsToRecipe;
    this.recipeSteps = input.recipeSteps ?? [];
  }
}
