// Code generated by gen_typescript. DO NOT EDIT.

export interface IValidInstrument {
  createdAt: NonNullable<string>;
  lastUpdatedAt?: string;
  archivedAt?: string;
  iconPath: NonNullable<string>;
  id: NonNullable<string>;
  name: NonNullable<string>;
  pluralName: NonNullable<string>;
  description: NonNullable<string>;
  slug: NonNullable<string>;
  displayInSummaryLists: NonNullable<boolean>;
  usedForStorage: NonNullable<boolean>;
}

export class ValidInstrument implements IValidInstrument {
  createdAt: NonNullable<string> = '1970-01-01T00:00:00Z';
  lastUpdatedAt?: string;
  archivedAt?: string;
  iconPath: NonNullable<string> = '';
  id: NonNullable<string> = '';
  name: NonNullable<string> = '';
  pluralName: NonNullable<string> = '';
  description: NonNullable<string> = '';
  slug: NonNullable<string> = '';
  displayInSummaryLists: NonNullable<boolean> = false;
  usedForStorage: NonNullable<boolean> = false;

  constructor(
    input: {
      createdAt?: string;
      lastUpdatedAt?: string;
      archivedAt?: string;
      iconPath?: string;
      id?: string;
      name?: string;
      pluralName?: string;
      description?: string;
      slug?: string;
      displayInSummaryLists?: boolean;
      usedForStorage?: boolean;
    } = {},
  ) {
    this.createdAt = input.createdAt ?? '1970-01-01T00:00:00Z';
    this.lastUpdatedAt = input.lastUpdatedAt;
    this.archivedAt = input.archivedAt;
    this.iconPath = input.iconPath ?? '';
    this.id = input.id ?? '';
    this.name = input.name ?? '';
    this.pluralName = input.pluralName ?? '';
    this.description = input.description ?? '';
    this.slug = input.slug ?? '';
    this.displayInSummaryLists = input.displayInSummaryLists ?? false;
    this.usedForStorage = input.usedForStorage ?? false;
  }
}

export interface IValidInstrumentCreationRequestInput {
  name: NonNullable<string>;
  pluralName: NonNullable<string>;
  description: NonNullable<string>;
  iconPath: NonNullable<string>;
  slug: NonNullable<string>;
  displayInSummaryLists: NonNullable<boolean>;
  usedForStorage: NonNullable<boolean>;
}

export class ValidInstrumentCreationRequestInput implements IValidInstrumentCreationRequestInput {
  name: NonNullable<string> = '';
  pluralName: NonNullable<string> = '';
  description: NonNullable<string> = '';
  iconPath: NonNullable<string> = '';
  slug: NonNullable<string> = '';
  displayInSummaryLists: NonNullable<boolean> = false;
  usedForStorage: NonNullable<boolean> = false;

  constructor(
    input: {
      name?: string;
      pluralName?: string;
      description?: string;
      iconPath?: string;
      slug?: string;
      displayInSummaryLists?: boolean;
      usedForStorage?: boolean;
    } = {},
  ) {
    this.name = input.name ?? '';
    this.pluralName = input.pluralName ?? '';
    this.description = input.description ?? '';
    this.iconPath = input.iconPath ?? '';
    this.slug = input.slug ?? '';
    this.displayInSummaryLists = input.displayInSummaryLists ?? false;
    this.usedForStorage = input.usedForStorage ?? false;
  }
}

export interface IValidInstrumentUpdateRequestInput {
  name?: string;
  pluralName?: string;
  description?: string;
  iconPath?: string;
  slug?: string;
  usedForStorage?: boolean;
  displayInSummaryLists?: boolean;
}

export class ValidInstrumentUpdateRequestInput implements IValidInstrumentUpdateRequestInput {
  name?: string;
  pluralName?: string;
  description?: string;
  iconPath?: string;
  slug?: string;
  usedForStorage?: boolean = false;
  displayInSummaryLists?: boolean = false;

  constructor(
    input: {
      name?: string;
      pluralName?: string;
      description?: string;
      iconPath?: string;
      slug?: string;
      usedForStorage?: boolean;
      displayInSummaryLists?: boolean;
    } = {},
  ) {
    this.name = input.name;
    this.pluralName = input.pluralName;
    this.description = input.description;
    this.iconPath = input.iconPath;
    this.slug = input.slug;
    this.usedForStorage = input.usedForStorage ?? false;
    this.displayInSummaryLists = input.displayInSummaryLists ?? false;
  }
}
