on: [ pull_request ]
name: Build webapp container
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Container
        run: |
          docker build --tag gcr.io/prixfixe-dev/webapp_server:${{  github.sha }} --file apps/web/Dockerfile .
          docker build --tag gcr.io/prixfixe-dev/webapp_server:latest --file apps/web/Dockerfile .
