on: [ pull_request ]
  pull_request:
    paths:
      - apps/**
      - packages/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Webapp Container
        run: |
          docker build --tag gcr.io/prixfixe-dev/webapp_server:${{  github.sha }} --file apps/web/Dockerfile .
          docker build --tag gcr.io/prixfixe-dev/webapp_server:latest --file apps/web/Dockerfile .
