on: # [pull_request]
 push:
   branches:
     - dev
name: dev webapp
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.DEV_GOOGLE_CLOUD_CREDENTIALS }}'

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build Container
        run: |
          docker build --tag gcr.io/prixfixe-dev/webapp_server:${{  github.sha }} --file apps/web/Dockerfile .
          docker build --tag gcr.io/prixfixe-dev/webapp_server:latest --file apps/web/Dockerfile .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.4
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}

      - name: Terraform Init
        working-directory: environments/webapp/dev/terraform
        id: init
        run: terraform init

      - name: Terraform Format
        working-directory: environments/webapp/dev/terraform
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: environments/webapp/dev/terraform
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: environments/webapp/dev/terraform

      - name: Push Container
        run: |
          docker push gcr.io/prixfixe-dev/webapp_server:${{  github.sha }}
          docker push gcr.io/prixfixe-dev/webapp_server:latest

      # if this step fails, you need to add the `Service Account User` role to the GitHub Actions IAM Principal.
      - id: deploy-webapp-server
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: 'webapp-server'
          project_id: 'prixfixe-dev'
          image: 'gcr.io/prixfixe-dev/webapp_server'
