on:
  pull_request:
    paths:
      - apps/**
      - packages/**
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['lts/*']
    name: ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - run: npm install -g yarn
      - run: yarn install

      - run: yarn run lint
