on:
  pull_request:
    paths:
      - environments/admin/dev/terraform/**
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.4
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN  }}

      - name: Terraform Init
        working-directory: environments/admin/dev/terraform
        id: init
        run: terraform init

      - name: Terraform Format
        working-directory: environments/admin/dev/terraform
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: environments/admin/dev/terraform
        id: validate
        run: terraform validate -no-color
